### ISSUE TITLE
Support ability to send Linkedin connection requests

### ISSUE THREAD

**Issue by tomquirk** [tomquirk/linkedin-api#10]
I.e. Add people on Linkedin

POST
```
{"trackingId":"XVpxyROJQ1ybTCQtEFrl8A==","invitations":[],"excludeInvitations":[],"invitee":{"com.linkedin.voyager.growth.invitation.InviteeProfile":{"profileId":"<profile_id>"}}}
```

to url
```
/voyager/api/growth/normInvitations
```

**Comment by igorench** [comment]
How can i get trackingId ?

**Comment by tomquirk** [comment]
mmm, i think the tracking ID might not matter? I haven't looked into it

**Comment by kingbar1990** [comment]
Can I send a connection via the add_connection () method? When I call him, the status code 500 comes from him.

**Comment by igorench** [comment]
Can I send a connection via the add_connection () method? When I call him, the status code 500 comes from him.

**Comment by tomquirk** [comment]
Nope, there's a reason it's commented out 😛 (it needs fixing)

**Comment by kingbar1990** [comment]
We was working on the issue for a weeks and did not find solution. 
Seems like we do the same as linkedin website except tracking_id.

@tomquirk do you have any ideas or suggestions?

**Comment by tomquirk** [comment]
Yea think you guys are right - looks like we need a tracking ID.

As far as I can tell, the tracking ID that they send isn't loaded in anywhere. I think they might generate it on the fly. I found this in the source:

```js
e.generateTrackingId = function() {
    var e=new Array(16)
    t.default.v4(null,e)
    return n(e)
}
```
Haven't tried it yet but looks promising

**Comment by tomquirk** [comment]
ooo, one more thing I found. There is this, which is in the source (from `<meta name="applicationInstance" ...>`

```js
trackingId: [83, -79, -16, -53, -34, 8, 72, -4, -113, -62, -119, 102, -23, 69, -110, 73]
```

Might be needed

**Comment by kingbar1990** [comment]
hi @tomquirk 

The script works - sends an invitations as expected.
We have to find the diff and implement in the library.
``
from bs4 import BeautifulSoup
import requests
import re
​
client = requests.Session()
​
# LInkedIn URL's and other variables
HOMEPAGE_URL = 'https://www.linkedin.com'
LOGIN_URL = 'https://www.linkedin.com/uas/login-submit'
MY_NETWORK = 'https://www.linkedin.com/mynetwork/'
​
INVITE_POST = 'https://www.linkedin.com/voyager/api/growth/normInvitations'
​
headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36', 'accept-encoding': 'gzip, deflate br', 'x-li-lang': 'en_US', 'accept-language': 'en-US,en;q=0.8', 'pragma': 'no-cache'}
​
# Connect with requests and pull csrf token.
def connect(username, password):
    html = client.get(HOMEPAGE_URL).content
    soup = BeautifulSoup(html, "html.parser")
    global csrf
​
    csrf = soup.find('input', {'name':'loginCsrfParam'})['value']
    login_information = {
        'session_key': username,
        'session_password': password,
        'loginCsrfParam': csrf,
    }
​
    client.post(LOGIN_URL, headers=headers, data=login_information)
​
def increase_network():
    linkedin_network = client.get(MY_NETWORK, headers=headers)
    # Pull out the JSESSIONID from the cookie header and set it as the CSRF Token.prob move this
    jsessionid = str(linkedin_network.request.headers['cookie']).split(';')[4:-4]
    jsessionid_join = str("".join(jsessionid))
    pattern = r'"([^"]*)"'
    a_join = re.findall(pattern, jsessionid_join)[0]
    csrf_token = str("".join(a_join))
    apicsrf = {
        'csrf-token': csrf_token
    }
​
    # Targeting User urn_id
    user_id = 'ACo.....'
    # Build the data
    data = '{"trackingId":"yvzykVorToqcOuvtxjSFMg==","invitations":[],"excludeInvitations":[],"invitee":{"com.linkedin.voyager.growth.invitation.InviteeProfile":{"profileId":' + '"' + user_id + '"' + '}}}'​
    post_invites = client.post(INVITE_POST, headers=apicsrf, data=data)
​
    return post_invites
​

if __name__ == '__main__':
    # Put your LinkedIn creds there
    linkedin_username = ''
    linkedin_pwd = ''
    connect(linkedin_username, linkedin_pwd)
    increase_network()
``

**Comment by kingbar1990** [comment]
@tomquirk Fixed
https://github.com/kingbar1990/linkedin-api/commit/a8bb9477a7bcb321b8e27af0e5031f45af1a1791#diff-a1bc635cadda7a23c9a01bd0728d859eR911

**Comment by tomquirk** [comment]
awesome, so looks like we def do need tracking id then. I think we should still try to generate this ourselves though. Haven't tested but I suspect recurring uses of the same tracking id might be problematic

**Comment by kingbar1990** [comment]
@tomquirk  in short - payload should be a string not a dict.

**Comment by arthunterme** [comment]
Is this function actually working?

**Comment by tomquirk** [comment]
Nope still needs to be implemented! :p

**Comment by hussaiy1** [comment]
@tomquirk did you find a solution to finding tracking id, i can see that add_connection function is still commented out

**Comment by aqibmumtaz** [comment]
@tomquirk  any update on add_connection?

**Comment by Gostuski** [comment]
> ooo, one more thing I found. There is this, which is in the source (from `<meta name="applicationInstance" ...>`
> 
> ```js
> trackingId: [83, -79, -16, -53, -34, 8, 72, -4, -113, -62, -119, 102, -23, 69, -110, 73]
> ```
> 
> Might be needed

@tomquirk what is the conversion needed to get a string out of this array?

**Comment by abinpaul1** [comment]
@tomquirk Would the below python code do to generate the `trackingid` . I have explained a bit more in the issue #133 
```python
import base64
from random import randrange
random_int_array = [randrange(256) for _ in range(16)]
rand_byte_array = bytearray(random_int_array)
trackingId = base64.b64encode(rand_byte_array)
```

**Comment by amirsohail12570** [comment]
Anyone tried to withdraw connection to a pending connection? I tried to use this endpoint but getting error 400.
/relationships/invitations?action=closeInvitations
Here's the code
![image](https://user-images.githubusercontent.com/78481079/127666603-f40645a1-bbef-4ada-8039-3c5012b71670.png)

**Comment by abinpaul1** [comment]
Please take a look at this branch
https://github.com/abinpaul1/linkedin-api/commit/ee20e616aa260cda52f7583e64f100702c47ca65

**Comment by amirsohail12570** [comment]
> > Anyone tried to withdraw connection to a pending connection? I tried to use this endpoint but getting error 400.
> > /relationships/invitations?action=closeInvitations
> > Here's the code
> > ![image](https://user-images.githubusercontent.com/78481079/127666603-f40645a1-bbef-4ada-8039-3c5012b71670.png)
> 
> Please take a look at this branch
> https://github.com/abinpaul1/linkedin-api/tree/add_withdraw_invitations

Thanks. It works!
