### ISSUE TITLE
Package fails to authenticate on Microsoft Azure, can't write your cookie files to read-only file system

### ISSUE THREAD

**Issue by ascooper57** [tomquirk/linkedin-api#107]
Package fails to authenticate on Microsoft Azure, can't write your cookie files to read-only file system.
Once pip installs your package linkedin_api, you can't write your linkedin_api/cookies/<email.jr> file since Azure makes the entire package folder and everything underneath it read-only. This results %100 of the time with a Linked in Authentication error (CHALLENGE). 

The problem in in settings.py
ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
COOKIE_PATH = os.path.join(ROOT_DIR, "cookies/")
Where it get the path to your file within the library itself. You can install your cookies above you library in the user's source code area, the "true root directory"

**Comment by crouinicrouina** [comment]
You probably won't be able to authenticate from Azure servers. Instead, you shoud package your app with the cookies (either with a cookiejar file or environment variables)

see https://github.com/tomquirk/linkedin-api/issues/109#issuecomment-691566813

**Comment by colemichae** [comment]
Change the file to look where it is being called from also I would change the name of the cookie. It should never write to a modules directory. :) 

Working on this now My Internet is really bad so I need to check Linkedin without all the overhead of the extra data they pull for the webpage, No currently don't have a Phone to access the Site, It died.. :( 

ROOT_DIR = os.getcwd()
#ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
COOKIE_FILE_PATH = os.path.join(ROOT_DIR, ".LIcookie.jr")

**Comment by tomquirk** [comment]
Thanks all, I've added the ability to pass in `cookies_dir` to `Linkedin()`, and also am now defaulting to something more sensible (`~/.linkedin_api`). Pretty sure it'll work cross-platform, but please create another issue if you have troubles

**Comment by ascooper57** [comment]
Thank you very much for this solution and your professionalism.

Alan S. Cooper
