### ISSUE TITLE
possible Search offset issue

### ISSUE THREAD

**Issue by CGann** [tomquirk/linkedin-api#118]
I do a search that has more than 10k results. Getting the first 1k results works just fine. However, if I enter an offset of 1000, I get zero results returned instead of the next 1000 results. 

Am I doing something wrong? I'm studying your code to try and grasp just how the limit and offset work together but I'm a bit confused.

**Comment by tomquirk** [comment]
Nope, it's LinkedIn. For any given query, the max result count is 1000, even if you set the offset at 1000. You can verify this in the UI as well - you wont get any results after the first 1000

**Comment by CGann** [comment]
Thank you, sir!cgSent from my phone. 
-------- Original message --------From: Tom Quirk <notifications@github.com> Date: 10/1/20  1:51 AM  (GMT-06:00) To: tomquirk/linkedin-api <linkedin-api@noreply.github.com> Cc: CGann <chris@chrisgannon.com>, Author <author@noreply.github.com> Subject: Re: [tomquirk/linkedin-api] possible Search offset issue (#118) 
Nope, it's LinkedIn. For any given query, the max result count is 1000, even if you set the offset at 1000. You can verify this in the UI as well - you wont get any results after the first 1000
