### ISSUE TITLE
couldn't able to extract company name and job description 

### ISSUE THREAD

**Issue by maazsofttech** [tomquirk/linkedin-api#122]
hi , first of all thanks for this amazing library , here i am  facing an  issue while using search_jobs () api 

i am not able to get company name and job description the only thing readable in result is apply url and time stamp 

here is the snippet i am getting in return 

`{"$type":"com.linkedin.voyager.jobs.OffsiteApply","applyStartersPreferenceVoid":true,"companyApplyUrl":"https://salesforce.wd1.myworkdayjobs.com/en-US/External_Career_Site/job/California---San-Francisco/Summer-2021-Intern---Infrastructure-Security-Assurance_JR73684-1?source=LinkedIn_Jobs"},"briefBenefitsDescription":"","companyDetails":{"$recipeTypes":["com.linkedin.voyager.deco.jserp.WebJobPostingWithCompanyName"],"$type":"com.linkedin.voyager.jobs.JobPostingCompany","*companyResolutionResult":"urn:li:fs_normalized_company:3185","company":"urn:li:fs_normalized_company:3185"},"duration":null,"entityUrn":"urn:li:fs_normalized_jobPosting:2163511482","expireAt":1604185119000,"formattedLocation":"Remote`

i am  not able to get company name and job description/company description

this is what i am getting regarding company 

`companyDetails":{"$recipeTypes":["com.linkedin.voyager.deco.jserp.WebJobPostingWithCompanyName"],"$type":"com.linkedin.voyager.jobs.JobPostingCompany","*companyResolutionResult":"urn:li:fs_normalized_company:3185","company":"urn:li:fs_normalized_company:3185"}`

**Comment by tomquirk** [comment]
Hey @maazsofttech just pushed a new version to master (not on PyPI) - let me know how you go

**Comment by maazsofttech** [comment]
@tomquirk  it seems that issue is not solved why are there vyoger links in the results like 
`$recipeTypes': ['com.linkedin.voyager.deco.jserp.WebJobPostingWithCompanyName']`
or 

`[{'salaryInsights': {'jobCompensationAvailable': False, '$type': 'com.linkedin.voyager.premium.SalaryInsights'}, 'dashEntityUrn': 'urn:li:fsd_jobPosting:2183530281', 'companyDetails': {'company': 'urn:li:fs_normalized_company:3195463', '*companyResolutionResult': 'urn:li:fs_normalized_company:3195463', '$recipeTypes': ['com.linkedin.voyager.deco.jserp.WebJobPostingWithCompanyName'], '$type': 'com.linkedin.voyager.jobs.JobPostingCompany'}, 'jobState': 'LISTED', 'title': 'Engineer - Software Development', 'duration': None, 'entityUrn': 'urn:li:fs_normalized_jobPosting:2183530281', 'briefBenefitsDescription': '', 'applyMethod': {'unifyApplyEnabled': False, 'type': 'CONTACT_INFORMATION', '$type': 'com.linkedin.voyager.jobs.SimpleOnsiteApply'}, '*savingInfo': 'urn:li:fs_jobSavingInfo:2183530281', 'new': False, 'formattedLocation': 'Gurugram, Haryana, India', 'expireAt': 1604138386000, 'listedAt': 1601546386000, '$recipeTypes': ['com.linkedin.voyager.deco.jserp.WebSearchJobJserpJobPostingWithSalary'], '$type': 'com.linkedin.voyager.jobs.JobPosting', 'standardizedAddresses': None, 'sourceDomain': None}, {'salaryInsights': {'jobCompensationAvailable': False, '$type': 'com.linkedin.voyager.premium.SalaryInsights'}, 'dashEntityUrn': 'urn:li:fsd_jobPosting:2011581663', 'companyDetails': {'company': 'urn:li:fs_normalized_company:2580522', '*companyResolutionResult': 'urn:li:fs_normalized_company:2580522', '$recipeTypes': ['com.linkedin.voyager.deco.jserp.WebJobPostingWithCompanyName'], '$type': 'com.linkedin.voyager.jobs.JobPostingCompany'}, 'jobState': 'LISTED', 'title': 'Software Development Engineer  I', 'duration': None, 'entityUrn': 'urn:li:fs_normalized_jobPosting:2011581663', 'briefBenefitsDescrip`


is it not  weird ?

**Comment by tomquirk** [comment]
Hmm, is that not the result you expect? That seems like a good amount of job data. I guess we eventually need a method `get_job_posting()` which would give you even more information. But, for a search, the data you show here is probably the best we can do

**Comment by maazsofttech** [comment]
ok thanks
