### ISSUE TITLE
get list of people work in particular company only yield the premium users

### ISSUE THREAD

**Issue by lavarthan** [tomquirk/linkedin-api#124]
`api.search_people(current_company=['1035'])` yield only the premium user account.

this is the URL generated
`https://www.linkedin.com/voyager/api/search/blended?count=49&filters=List(resultType-%3EPEOPLE,currentCompany-%3E1035)&origin=GLOBAL_SEARCH_HEADER&q=all&start=0&queryContext=List(spellCorrectionEnabled-%3Etrue,relatedSearchesEnabled-%3Etrue,kcardTypes-%3EPROFILE%7CCOMPANY)`

**Comment by lavarthan** [comment]
I found the solution 
The account I used here is a new one, make some connection and follow companies it will give you access more broadly

**Comment by tomquirk** [comment]
Yep, thats the trick :)
