### ISSUE TITLE
`search_jobs` doesn't work

### ISSUE THREAD

**Issue by khangly** [tomquirk/linkedin-api#125]
I got this error:
```python3
jobs = api.search_jobs(keywords='software engineer',experience='2',job_type='F')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-e8676eef6663> in <module>()
----> 1 jobs = api.search_jobs(keywords='software engineer',experience='2',job_type='F')

TypeError: search_jobs() got an unexpected keyword argument 'experience'
```
I installed with
```
pip3 install linkedin-api~=2.0.0a
```

**Comment by pandrey2003** [comment]
Agree, I have the same problem with the `search_people` function.

**Comment by pandrey2003** [comment]
> Agree, I have the same problem with the `search_people` function.

I think you need to uninstall the library and install it again with `pip3 install linkedin-api~=2.0.0a`. It worked for me

**Comment by pandrey2003** [comment]
> > Agree, I have the same problem with the `search_people` function.
> 
> I think you need to uninstall the library and install it again with `pip3 install linkedin-api~=2.0.0a`. It worked for me

Does not seem to work with the `search_people` function...

**Comment by ankurGhosh1** [comment]
I am trying to filter the jobs by particular company and have written the following line for retrieving the data: 
`jobs = api.search_jobs(companies=['30204141'], location_name="India", limit=3)`

This does not seem to work for the company but the limit and location works fine. I was thinking it might be a URN ID issue (might have misunderstood the URN ID). Here is the link for the job: `https://www.linkedin.com/jobs/search/?f_C=30204141&location=Worldwide` Can someone point me out the correct URN ID I am using '30204141' as the URN ID in the above example.

**Comment by ssichynskyi** [comment]
@ankurGhosh1 
if this is urgent, you may use libs from here: https://github.com/ssichynskyi/linkedin-api/tree/ultimate_jobs_fix
your issue is solved there (as well as all other related to search_job function). I've made a pull request to the main repo, but seems it's going to take some time.

**Comment by ankurGhosh1** [comment]
@ssichynskyi I tried out your branch and it works but not for all companies. I am sharing the code I used to get all jobs for `google (URN: 1441) ` and it worked but it does not work for other `companies with such as with (URN: 30204141) `. Here is the code I used. Thanks

```
@api_view(['GET',])
@permission_classes((permissions.AllowAny,))
def openroles(request):
    api = Linkedin('my@email.com', '########')

    jobs = api.search_jobs(companies=['30204141'], location_name="Worldwide", limit=3)   # Does not work
    jobs = api.search_jobs(companies=['1441'], location_name="Worldwide", limit=30)  # Works 
    print(jobs)

    return Response(jobs)
```

**Comment by ssichynskyi** [comment]
@ankurGhosh1 it works as expected. The company you refer to, has one open Job position, which was posted ~ 2 weeks ago. Default time settings provides search for job postings that are not more than 24 hours old.
So, make request this way:
jobs = api.search_jobs(companies=['30204141'], location_name="Worldwide", listed_at=86400*30, limit=3)

and it will work ;-)

**Comment by ankurGhosh1** [comment]
Hey @ssichynskyi, this works absolutely fine. Thank you for the explanation.

**Comment by ssichynskyi** [comment]
@khangly, @pandrey2003, kindly ask you to re-check after a significant rework of search_job functionality. I assume it shall work now, (unless linkedin haven't banned all job-related requests). Could you please confirm?

**Comment by ssichynskyi** [comment]
Closing this. If someone experience the same, please comment here or create a new issue.
