### ISSUE TITLE
This package cannot be called

### ISSUE THREAD

**Issue by lxppx** [tomquirk/linkedin-api#126]
I'm a beginner learning python，I use it in your way, can you tell me where the mistake is?
![222](https://user-images.githubusercontent.com/42337441/96325767-50e32b00-105d-11eb-8f18-15cea126a193.png)
![333](https://user-images.githubusercontent.com/42337441/96325770-517bc180-105d-11eb-88a8-165da859946e.png)

**Comment by pandrey2003** [comment]
Please, close this issue. It is **your** problem you do not know Python, not the issue of the library.

**Comment by tomquirk** [comment]
Hey @lxppx, that's a bit strange. Your code looks perfectly fine, those arguments should not be required.

1. What version of `linkedin-api` are you using? (how did you install it)
2. What version of Python are you using (type `python -V` into your terminal)

@pandrey2003 thanks for the comment but I'm more than happy to help anyone use the library, no matter their experience 😄
