### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by keducoop** [tomquirk/linkedin-api#129]
Hi there.

First of all many thanks to all the people involved in this project for their time, we really appreciate it.

## Steps to reproduce

1. Clone the project

```
git clone https://github.com/tomquirk/linkedin-api 
cd linkedin-api 
```

2. Launch ipython

```iptyhon3```

3. Type

```
from linkedin_api import Linkedin

# Authenticate using any Linkedin account credentials
api = Linkedin('user@example.com', 'secret')

# GET a profile
profile = api.get_profile('billy-g')
```

## Expected behaviour

Get some python output

## Found behaviour

Below error:

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    api = Linkedin('user@example.com', 'secret')
  File "/tmp/aux/linkedin-api/linkedin_api/linkedin.py", line 69, in __init__
    self.client.authenticate(username, password)
  File "/tmp/aux/linkedin-api/linkedin_api/client.py", line 102, in authenticate
    self._do_authentication_request(username, password)
  File "/tmp/aux/linkedin-api/linkedin_api/client.py", line 166, in _do_authentication_request
    self._cookie_repository.save(res.cookies, username)
  File "/tmp/aux/linkedin-api/linkedin_api/cookie_repository.py", line 28, in save
    self._ensure_cookies_dir()
  File "/tmp/aux/linkedin-api/linkedin_api/cookie_repository.py", line 41, in _ensure_cookies_dir
    if not os.path.exists(self.cookies_dir):
  File "/usr/lib/python3.8/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by oujbih** [comment]
same problem

**Comment by lcarcamo1526** [comment]
Same problem here, looks credentials login will not work, instead we should use cookies

**Comment by burakyilmaz321** [comment]
Hi all ✋ , I opened a PR for this. See https://github.com/tomquirk/linkedin-api/pull/130.

**Comment by tomquirk** [comment]
Sorry about this everyone. The issue is fixed in v2.0.0-alpha.5

**Comment by marcelogrsp** [comment]
> Same problem here, looks credentials login will not work, instead we should use cookies

Hi @lcarcamo1526 , How are you getting cookies and using them?

**Comment by lcarcamo1526** [comment]
If I remember properly I got cookies manually from the browser, on Firefox you can open developer options on the Network tab I looked for some request (could enter into a profile), the trick its identify the right request and the copy as curl, you'll get all the details of the request, including the cookies (if I remember well you will have to convert into some file and at the time to call the function you should link with its path), you could even replicate some functions of the library replicating its endpoint and the playing with some parameters.
