### ISSUE TITLE
TrackingId

### ISSUE THREAD

**Issue by Gostuski** [tomquirk/linkedin-api#133]
Yea think you guys are right - looks like we need a tracking ID.

As far as I can tell, the tracking ID that they send isn't loaded in anywhere. I think they might generate it on the fly. I found this in the source:

```js
e.generateTrackingId = function() {
    var e=new Array(16)
    t.default.v4(null,e)
    return n(e)
}
```
Haven't tried it yet but looks promising

_Originally posted by @tomquirk in https://github.com/tomquirk/linkedin-api/issues/10#issuecomment-518408809_

I would appreciate if you could tell me where did you find this code snippet.
I managed to make a function that returns a tracking id that size and format but linkedin sometimes fails to  process my request that contains it and returns status 500.
I checked every case and the problem is trackingId. 
Thnaks in advance.
Dusan.

**Comment by abinpaul1** [comment]
Its available in this file present in `static-exp1.licdn.com` folder on the website
https://static-exp1.licdn.com/sc/h/dcrzl71jllw4dwf6vtd7yn7x9

**Comment by abinpaul1** [comment]
After a bit more trial and error it seems tracking id is generated as below:
```javascript
var e = window.crypto
var t = new Uint8Array(16)
var trackingid = i(t) //where i is the function defined in the above comment's first code snippet
```
