### ISSUE TITLE
Help searching for companies

### ISSUE THREAD

**Issue by OrgesKreka** [tomquirk/linkedin-api#134]
Hi,
I need help searching for companies in a specific area ( Albania ) i have tried passing the keyword 'Albania' as a parameter but it doesn't filter anything.
After looking the linkedin documentation it needs a country code as a parameter but Albania is no there:
https://docs.microsoft.com/en-us/linkedin/shared/references/reference-tables/geography-codes?context=linkedin/marketing/context
But if i try searching from the website, it sends a request like this:

> count=10&filters=List(geoUrn-%3E102845717,resultType-%3EPEOPLE)&keywords=foo&origin=FACETED_SEARCH&q=all&queryContext=List(spellCorrectionEnabled-%3Etrue,relatedSearchesEnabled-%3Etrue)&start=0

Please someone help me how to convert this query as a keyword for the search_companies method.

**Comment by favcau** [comment]
You can't search for companies in a specific country/area (neither on linkedin.com), but you can search for companies with the word Albania in their name.
Note that in **search_companies()**, the parameter **keywords** must be a list, so you should pass `keywords=['Albania']`

PS: The country code for Albania is AL

**Comment by OrgesKreka** [comment]
Thank You for the response @favcau
