### ISSUE TITLE
Location job_search()

### ISSUE THREAD

**Issue by kingducks** [tomquirk/linkedin-api#144]
When searching for jobs by location, the returned jobs do not seem to adhere to the specified location. 

Using these parameters:
`"keywords": "machine learning data",
            "location": "denmark",
            "limit": 1,`

The jobs returned show various locations not in denmark. Additionally, this is the url that is called by job_search():
`https://www.linkedin.com/voyager/api/search/hits?decorationId=com.linkedin.voyager.deco.jserp.WebJobSearchHitWithSalary-14&count=1&filters=List(%5B%27resultType-%3EJOBS%27,+%27locationFallback-%3Edenmark%27,+%27commuteFeatures-%3Ef_WRA%27%5D)&origin=JOB_SEARCH_RESULTS_PAGE&q=jserpFilters&start=0&queryContext=List(primaryHitType-%3EJOBS,spellCorrectionEnabled-%3Etrue)&keywords=machine+learning+data`

When I search for jobs in Denmark manually on the website from the account that I used to login with Linkedin() constructor, job_search() function finally returns Denmark results. However, if I try to switch the location in job_search() again, my results become stuck at Denmark, until I visit the website and manually search in the US.

This sounds like an issue with the cookies, but it makes the locality search problematic.

**Comment by ssichynskyi** [comment]
@kingducks should be fixed now. (Unless linkedin haven't banned all job-related requests). Could you please confirm?

**Comment by ssichynskyi** [comment]
Closing this. If someone experience the same, please comment here or create a new issue.
