### ISSUE TITLE
remote = True is not working

### ISSUE THREAD

**Issue by cagatay135** [tomquirk/linkedin-api#147]
I Want to display remote working jobs but is not working.
jobX = api.search_jobs(keywords='Assistant Account Manager', job_type=['F'], location_name='United States', remote = [True] , listed_at=1, limit=1, offset=10)

**Comment by ssichynskyi** [comment]
@cagatay135, should be fixed now. (Unless linkedin haven't banned all job-related requests). Could you please confirm?

**Comment by ssichynskyi** [comment]
Closing this. If someone experience the same, please comment here or create a new issue.
