### ISSUE TITLE
How to get public_id and urn_id

### ISSUE THREAD

**Issue by pinnamaneni2005** [tomquirk/linkedin-api#150]
Is there a way to get public_id and urn_id using the API once we are connected using below statement:

api = Linkedin('aaaaaaaaaaaaaaa@profile.com', '********')

The same way we are getting other profile details, just by using the linkedin username and password.

**Comment by pinnamaneni2005** [comment]
Or can we get the profile url, so that from there we can get the public_id

**Comment by pinnamaneni2005** [comment]
I got what I am looking for thanks all.

**Comment by jatinvinkumar** [comment]
@pinnamaneni2005 how did you get the urn for a person?
