### ISSUE TITLE
Linkedin Session Expired Exceptions

### ISSUE THREAD

**Issue by alexanderfeinberg** [tomquirk/linkedin-api#151]
I'm not really sure how to get around this exception in order to log back in using this API. All accounts I've used this API on previously are receiving the LinkedinSessionExpired exception, so the cookies are expired, any suggestions on how to reauntheticate and get new cookies using the API?

**Comment by ssichynskyi** [comment]
@alexander1fein , have you tried something like this?
linkedin = Linkedin(*credentials, **refresh_cookies=False**)

**Comment by alexander1fein** [comment]
Yes, it didn't work, neither did cookies=None and cookies_dir=None

**Comment by ssichynskyi** [comment]
@alexander1fein for me this changing refresh_cookies from default to True fixed the problem.
