### ISSUE TITLE
linkedin_api.client.ChallengeException: CHALLENGE

### ISSUE THREAD

**Issue by Vikku14** [tomquirk/linkedin-api#162]
As mentioned in Readme. Challenge error is coming because of continuous requests. But it is not true in my case. CHALLENGE error is coming after 1st request. After some analysis, I found out that this is happening after executing **self.client.authenticate(username, password)** function
in **linkdedin.py** file.
After executing this script one-time LinkedIn in sending me following mail:

> Hi XYZ,
>  
> To  make sure you continue having the best experience possible on LinkedIn,  we're regularly monitoring our site and the Internet to keep your  account information safe.
> We've  recently noticed a potential risk to your LinkedIn account coming from  outside LinkedIn and just to be safe, we've locked your account for now.  You'll need to reset your password in order to unlock your account.  Here's how:
> Go to the LinkedIn website. Next to the password field, click the "Forgot your password" link, and enter your email address. You'll get an email from LinkedIn asking you to click a link that will help you reset your password. Once you've reset your password, a confirmation email will be sent to the confirmed email addresses on your account.

**Comment by flcong** [comment]
Same here.

**Comment by flcong** [comment]
I find that if you first log into the Linkedin account in a browser and then on the same computer, run `api = Linkedin('username', '*******')`, it won't raise the error and at the same time in the browser the login is kicked out.

**Comment by amoghadithya** [comment]
I got the same error, in my case the it's just after you do the authenticate login, there is a few seconds during which you can extract data, then the login resets and the CHALLENGE Exception occurs.

**Comment by flcong** [comment]
> I got the same error, in my case the it's just after you do the authenticate login, there is a few seconds during which you can extract data, then the login resets and the CHALLENGE Exception occurs.

Yeah. and one has to reset the password every time. It seems not feasible anymore.

**Comment by shabri-arrahim** [comment]
Does anyone have a solution to this problem?

**Comment by flcong** [comment]
> Does anyone have a solution to this problem?

I end up using Selenium to parse on my own...

**Comment by adityaalifn** [comment]
looks like @flcong is correct. I need to open my linkedin profile locally and then use the library. it works!

but after I deploy my app, it does not work :(
any idea how to fix this? can we implement cookies or something?

**Comment by tomquirk** [comment]
https://github.com/tomquirk/linkedin-api#i-keep-getting-a-challenge

**Comment by Suhani-shri** [comment]
Linkedin() work on local but on server give linkedin_api.client.ChallengeException: CHALLENGE

**Comment by s-python-code** [comment]
This Linkedin(email, password) function gives a Linkedin challenge exception on EC2 server,
It works for 2-3 weeks without any error but again gives a LinkedIn challenge exception.

**Comment by kmsky** [comment]
> This Linkedin(email, password) function gives a Linkedin challenge exception on EC2 server, It works for 2-3 weeks without any error but again gives a LinkedIn challenge exception.

Do you find any solution? I have similar problem with EC2 server

**Comment by AmirRezaM75** [comment]
I logged out from browser, and it works

**Comment by Nasim004** [comment]
Did anyone find any solution for this ? No issue is showing in my PC but when I shared this to another PC the CHALLENGE Exception is showing.

**Comment by AdrienDIDIER** [comment]
Had the same error today. Not on my local env. But as soon as i tried to used the version deployed in kubernetes it fail. And i'm only using post request so i can even pass the capcha. Any help on this ?

**Comment by Farazzaidi22** [comment]
> I logged out from browser, and it works

This is the solution. Thank you so much

**Comment by Pratham1209** [comment]
> I logged out from browser, and it works

Could you please explain in detail? I'm facing issues after deploying it on render.

**Comment by AmirRezaM75** [comment]
> > I logged out from browser, and it works
> 
> Could you please explain in detail? I'm facing issues after deploying it on render.

No details. Log out from Linkedin in all devices.
