### ISSUE TITLE
Messaging Payload Changed - Requires 2 more IDs

### ISSUE THREAD

**Issue by adeveloperhere** [tomquirk/linkedin-api#168]
So, 

This is the new payload

`{"conversationCreate":{"eventCreate":{"originToken":"2e067c75-e828-4187-91de-07c27dfc71e0","value":{"com.linkedin.voyager.messaging.create.MessageCreate":{"attributedBody":{"text":":)","attributes":[]},"attachments":[]}},"trackingId":"r?b??-?uA?<??V1K"},"recipients":["ACoAADBcXGsBpL-rFEUAnnOUesqYDTw4"],"subtype":"MEMBER_TO_MEMBER"}}`

As you can see 2 new IDs are here

1. originToken
2. trackingId

originToken is - a GUID nothing else
trackingId is a  bytearrayto string converted ASCII data

this trackingId's re uniqueue and if someone tries to send message with 

Uint16Array[16] thento ASCII string - sometimes it works but looks like there is more check. I do not have the ability. 

These being generated from this JS file 
https://static-exp1.licdn.com/sc/h/3fpvgp139ytyncvhp1ke3qejn

suspected methods you will see there are :

generateByteString()
generateTrackingId()

Please fix. :)

**Comment by abinpaul1** [comment]
```javascript
function generateTrackingId(){
  var n = new Array(16)
  for (var e, t = 0; t < 16; t++) {
                    0 == (3 & t) && (e = 4294967296 * Math.random())
                    n[t] = e >>> ((3 & t) << 3) & 255
                }
  let i = ""
  for (let ii = 0; ii < n.length; ii++)
      i += String.fromCharCode(n[ii])
  return i
}

// https://stackoverflow.com/questions/105034/how-to-create-a-guid-uuid/2117523#2117523
function getOriginToken() {
  return ([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g, c =>
    (c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16)
  );
}
```
I tried using the above functions to create the parameters and send requests and it seems to work.
@adeveloperhere Can you try with these to generate and confirm

**Comment by adeveloperhere** [comment]
> 
> 
> ```js
> function generateTrackingId(){
>   var n = new Array(16)
>   for (var e, t = 0; t < 16; t++) {
>                     0 == (3 & t) && (e = 4294967296 * Math.random())
>                     n[t] = e >>> ((3 & t) << 3) & 255
>                 }
>   let i = ""
>   for (let ii = 0; ii < n.length; ii++)
>       i += String.fromCharCode(n[ii])
>   return i
> }
> 
> // https://stackoverflow.com/questions/105034/how-to-create-a-guid-uuid/2117523#2117523
> function getOriginToken() {
>   return ([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g, c =>
>     (c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16)
>   );
> }
> ```
> 
> I tried using the above functions to create the parameters and send requests and it seems to work.
> @adeveloperhere Can you try with these to generate and confirm

Just to correct - 

the generatetrackingId is not where it is being generated. For me i had issues but if is working for you is great then but someone who knows linkedin can fix it. I urge the maintainer to add the function so the messaging feature gets restored. 

I am not from Python so can not share a solution but @abinpaul1 if you are then submit a fix to @tomquirk  so he can  add it.  :)

I tried my best to locate the data used. 


Thanks All

**Comment by abinpaul1** [comment]
@adeveloperhere I have opened a pull request for this. Try it out and let me know if it works for you as well. 
The build seems to be failing because of some formatting issues.
