### ISSUE TITLE
Add ability to "view" a profile

### ISSUE THREAD

**Issue by tomquirk** [tomquirk/linkedin-api#17]
View someones profile, such that they get a notification that you "viewed their profile" 👀 .

### Request

```js
fetch("https://www.linkedin.com/li/track", {
  headers: {
    accept: "*/*",
    "accept-language": "en-AU,en-GB;q=0.9,en-US;q=0.8,en;q=0.7",
    "cache-control": "no-cache",
    "content-type": "text/plain;charset=UTF-8",
    pragma: "no-cache",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "no-cors",
    "sec-fetch-site": "same-origin",
    cookie: "redacted",
  },
  referrer: "https://www.linkedin.com/in/tom-quirk/",
  referrerPolicy: "no-referrer-when-downgrade",
  body: JSON.stringify(body),
  method: "POST",
  mode: "cors",
})
```

Where `body` is:

```js
const body = {
    eventBody: {
      viewerPrivacySetting: "F",
      networkDistance: 2,
      vieweeMemberUrn: "urn:li:member:111111111", // target profile member URN
      // miniprofile Tracking Id
      profileTrackingId: "redacted",
      entityView: {
        viewType: "profile-view",
        viewerId: 222222222, // my member URN id (int)
        targetId: 111111111, // target profile member URN id (int)
      },
      header: {
        pageInstance: {
          pageUrn: "urn:li:page:d_flagship3_profile_view_base",
          // meta [name=clientPageInstanceId]
          trackingId: "redacted",
        },
        time: Date.now(),
        version: "1.6.8780",
        clientApplicationInstance: {
          applicationUrn: "urn:li:application:(voyager-web,voyager-web)",
          version: "1.6.8780",
          // meta[name=applicationInstance].content.trackingId
          trackingId: [
            // redacted
          ],
        },
      },
      requestHeader: {
        interfaceLocale: "en_US",
        pageKey: "d_flagship3_profile_view_base",
        path: "/in/tom-quirk/",
        referer: "https://www.linkedin.com/feed/",
      },
    },
    eventInfo: {
      appId: "com.linkedin.flagship3.d_web",
      eventName: "ProfileViewEvent",
      topicName: "ProfileViewEvent",
    },
  }
```

So, we need to get three pieces of data from the source HTML of the given profile for the body of our request:

- `clientApplicationInstance.trackingId`: get this from the meta tag of selector `meta[name=applicationInstance]`
- `pageInstance.trackingId`: from selector `meta[name=clientPageInstanceId]`
- `profileTrackingId`: from the miniprofile

**Comment by JannikZed** [comment]
Hi there, 
I was kind of trying to achieve the same thing and made some tests - I'm not sure, if this request worked. For me it just worked, when you "proved" to linkedin that your click was coming out of the Linkedin search (for example by setting the querystring they also set when clicking on a profile you found via their search).
Seems like they want limit this view.

**Comment by tomquirk** [comment]
@JannikZed I found it 😁 😁 😁 . I've updated the description with the details. I will aim to implement this soon 👍

**Comment by JannikZed** [comment]
amazing! I don't fully understand, how you did it. Using /li/track somehow?

**Comment by serv0id** [comment]
Hi, 
I'm trying to implement the automation of Linkedin Learning's (formerly known as Lynda) courses using the same /li/track endpoint that you mention here, but have been mostly unsuccessful. Their
