### ISSUE TITLE
google cloud function

### ISSUE THREAD

**Issue by PMLS3** [tomquirk/linkedin-api#170]
Has someone tried google functions with? I keep on getting the same error doesn't matter what I try. 
The error seems to kick in on authentication
![Screenshot_1](https://user-images.githubusercontent.com/62140524/123643683-eeb20b00-d824-11eb-9526-da9e214a09a8.png)

**Comment by boyesm** [comment]
The issue is with the IP address used to make the connection. Linkedin blocks all data centre IPs so you would need to use a non-data centre proxy in order to get around it.

**Comment by Darebear21** [comment]
I fixed this issue by including my cookies file in my source directory and adjusting some path variables as needed.
