### ISSUE TITLE
CHALLENGE error

### ISSUE THREAD

**Issue by vethssvikas** [tomquirk/linkedin-api#176]
Hello all!
when i enter my email address and password i get a 'CHALLENGE' error.
How do i overcome the same?
Thanks!!!!

**Comment by abinpaul1** [comment]
Maybe try logging in from that IP address through browser a couple of times and then try again.
A sort of workaround is discussed in #109

**Comment by vethssvikas** [comment]
ah, how do i do that, could you please enlighten me ? i am confused!

**Comment by abinpaul1** [comment]
> ah, how do i do that, could you please enlighten me ? i am confused!

https://github.com/tomquirk/linkedin-api/issues/109#issuecomment-853808258

The script mentioned might work. Please try.

**Comment by ssichynskyi** [comment]
> ah, how do i do that, could you please enlighten me ? i am confused!

@vethssvikas, which functionality of this lib have you used before the challenge error? Have you tried job search?

**Comment by abinpaul1** [comment]
Closing this for now. @vethssvikas feel free to reopen if needed.
