### ISSUE TITLE
api.get_profile_connections("username") returning 1000 connections every time

### ISSUE THREAD

**Issue by mhmzdev** [tomquirk/linkedin-api#178]
Although its mentioned in the doc that `api.get_profile_connections()` gets you **1st Degree Connection** Yet it is returning a list of 1000 connections even if the profile has 5 connections.

Below is the code:
```python
from linkedin_api import Linkedin
api = Linkedin("email", "password")
connection = api.get_profile_connections("mhmzdev")
```

**Comment by abinpaul1** [comment]
The get_profile_connections takes URI as input and not the public profile name. 
However there does seem to be a bug when we give the URI of an account with no mutual connections. In this case a list of connections( I believe it is our own connections) is returned
