### ISSUE TITLE
Connections endpoint returning empty 

### ISSUE THREAD

**Issue by alvaroserrrano** [tomquirk/linkedin-api#179]
I am trying to get the connections for a profile by entering the urn_id of the profile as a parameter but I keep getting an empty array []. Is there any extra information I might be missing making the request? The session with the cookies is already in place and I am calling it `api.get_profile_connections("xxxxxxxx")` where xxxx is the urn_id of a public. 

Also, is there any other medium of communication for contributors of this project? 

Thanks

**Comment by abinpaul1** [comment]
Your understanding is right. The `get_profile_connections` method takes in urn_id as parameter. (An example of a urn_id is  `ACoAAAASIIYBAupwYeodMQ66KTxzMDHmajFq7Uw`)
An empty list is usually returned when the user who you are connecting to does not have first degree connections with you.

**Comment by abinpaul1** [comment]
Closing for now. Please do reopen if the issue persists if possible with an example to better debug.
