### ISSUE TITLE
Improve authentication "anti-bot-detection" mechanism

### ISSUE THREAD

**Issue by xiaoyongzhu** [tomquirk/linkedin-api#18]
Not sure if you've encountered this case, but the authentication sometimes doesn't work for me. The following exception will be thrown out:

```
res.status_code 401
Traceback (most recent call last):
  File "F:/linkedin-api/examples/basic.py", line 60, in <module>
    linkedin = Linkedin(credentials['username'], credentials['password'])
  File "F:\linkedin-api\linkedin_api\linkedin.py", line 30, in __init__
    self.client.authenticate(username, password)
  File "F:\linkedin-api\linkedin_api\client.py", line 102, in authenticate
    raise Exception()
Exception
```

I am thinking it might be the case that LinkedIn is blocking the API for some reason, but the account itself is fine (I can still login thru the web portal) - so I am wondering if you've encountered this before?

**Comment by xiaoyongzhu** [comment]
BTW I've also tried to clear the cookies but with no luck:(

**Comment by tomquirk** [comment]
Hey @xiaoyongzhu , I haven't run it in a while but can't recall such an issue. I will check it out though, and happy to consider any fixes you might have.

It's a good sign you can still log in as normal - at least they haven't blocked you 😂

**Comment by mbande** [comment]
same issue here, response data is as this:
```json
{'challenge_url': 'https://www.linkedin.com/uas/direct-login-submit?dropLiatCookie=drop&addDetailedLoginResult=add&csrfToken=ajax%3A7013480275436769896&submissionId=Login%3A04554a36-a324-4153-b5b6-d037f3dbd6b4', 'login_result': 'CHALLENGE'}
```

**Comment by tomquirk** [comment]
mmm, sorry still haven't had a chance to look myself, but I do recall encountering `"login_result": "CHALLENGE"` early on... will keep you posted once I investigate

**Comment by xiaoyongzhu** [comment]
I highly suspect it's because we've triggered some LinkedIn anti-bot mechanism, since sometimes when I login to the account, I met the captcha challenge, while in some of the cases I don't meet that...

**Comment by tomquirk** [comment]
Alright, well I just tried it and I'm all good. @xiaoyongzhu I'd say your 100% right - you guys `t r i g g e r e d` them 😂 

Let's keep this issue open to discuss ways of resolving this.

So, to kick off the discussion...

To my surprise, we're actually not doing anything to mitigate this for authentication. In [other spots](https://github.com/tomquirk/linkedin-api/blob/master/linkedin_api/linkedin.py#L166), we add a random, short delay. To my knowledge, it seems to be working pretty nicely.

So I say we do 2 things

1. Add the random delay to auth
2. Cache the session somehow so we don't need to hit the auth endpoint every time. *(this will almost certainly fix all our issues I think)*

**Comment by xiaoyongzhu** [comment]
Agree Tom. I suspect the second way will be much better (though I don't know how to do it since I don't have background in this area). Another data point is that it can run successfully in the other machine, so the banning mechanism is not bundled with account but with IP address I guess.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tomquirk** [comment]
ah very nice, good to know about the IP addresses, might be good to add that to README.

Re: session caching, I'll have a look. Pretty sure there will be a simple way using `requests`

**Comment by mbande** [comment]
tried with multiple IP's with no success.
somehow strange thing is that i get HTTP code 401, witch seems not relevant
