### ISSUE TITLE
search_people()

### ISSUE THREAD

**Issue by awesomezane** [tomquirk/linkedin-api#188]
Was there an update on the parameters, I tried and it returned errors on some of the parameters such as keywordd_first_name, keyword_last_name, some others. Is there a replacement for the keyword_last_name one?

**Comment by J-Obog** [comment]
> Was there an update on the parameters, I tried and it returned errors on some of the parameters such as keywordd_first_name, keyword_last_name, some others. Is there a replacement for the keyword_last_name one?

I'm having the same issue, I tried searching by title and got the same error. What I did was just put the title in the keywords parameter and it worked ok. Hope this helps.
