### ISSUE TITLE
where to find this link and how it is generated pls explain in detail !!!!

### ISSUE THREAD

**Issue by js-stark** [tomquirk/linkedin-api#189]
https://www.linkedin.com/voyager/api/search/blended?count=10&filters=List(currentCompany-%3E{},resultType-%3EPEOPLE)&origin=COMPANY_PAGE_CANNED_SEARCH&q=all&queryContext=List(spellCorrectionEnabled-%3Etrue)&start={}

Working with a LinkedIn Scrapper got me into this link, but I am unable to find it in the Networks Tab from inspect element or anywhere else.

Pls explain where is this link generated and how to find it with any tool or something else..

**Comment by alvaroserrrano** [comment]
Navigate to linkedin with Developer tools open in Chrome. In the network tab, try filter as '/voyager' and you can see the endpoints and the body of the request being sent and the response as well.

**Comment by js-stark** [comment]
https://www.linkedin.com/voyager/api/organization/companies?decorationId=com.linkedin.voyager.deco.organization.web.WebFullCompanyMain-37&q=universalName&universalName=amzon

I could find something like this ,but not the above link with "blended?count=10&filters", anywhere, pls tell where to find a similar link or where to navigate

**Comment by alvaroserrrano** [comment]
Did you try setting the filters manually on the Linkeding website and recording the network traffic with devtools?

**Comment by js-stark** [comment]
Yeah I tried manually with filters, but I could not find the exact link as above, also I'm not sure at which LinkedIn page this request is getting sent.

**Comment by abinpaul1** [comment]
Sorry!. I dont think we'll be able to help you in this case. I think your best bet would be as mentioned above to keep recording the network and browse around Linkedin. Try different kinds of search with different filters and keep checking the requests. I am guessing you might have tried this already. 
If you can detail any particular use case in my mind for which you need this endpoint, maybe we could suggest something different.

**Comment by abinpaul1** [comment]
Closing this for now. Feel free to reopen if you want to continue the discussion.
