### ISSUE TITLE
Support Company Search

### ISSUE THREAD

**Issue by Alexander-Bakogeorge** [tomquirk/linkedin-api#19]
No ability to search companies, looking into this now :)

**Comment by Alexander-Bakogeorge** [comment]
Only had luck so far with these params in the blended search, fails when I run a clustered search. @tomquirk is this an issue you've ran into before?
```
default_params = {
            "origin": "GLOBAL_SEARCH_HEADER",
            "guides": "List(resultType->companies)",
            "count": "10",
            "q": "guided",
            "filters": "List(resultType->companies)",
            "start": len(results)
}
res = self.client.session.get(
            f"{self.client.API_BASE_URL}/search/blended?origin=SWITCH_SEARCH_VERTICAL&count=10&q=all&filters=List(resultType-%3Ecompanies)&start={len(results)}"
)
```

**Comment by Alexander-Bakogeorge** [comment]
Sorry for deleting my last comment, noticed a few dumb errors 😢 , regardless

When I try sending params to the search function, such as

```
default_params = {
            "origin": "GLOBAL_SEARCH_HEADER",
            "guides": "List(resultType->companies)",
            "count": "10",
            "q": "guided",
            "filters": "List(resultType->companies)",
            "start": len(results)
        }
```

I get returned a list of people, instead of companies. So far, the only thing that's worked for me is a blended search, with the params in the query string.

```
res = self.client.session.get(
            f"{self.client.API_BASE_URL}/search/blended?origin=GLOBAL_SEARCH_HEADER&count=10&guides=List(resultType-%3Ecompanies)&q=all&filters=List(resultType-%3Ecompanies)&start={len(results)}"
        )
```

@tomquirk have you experienced any similar issues before?

**Comment by tomquirk** [comment]
Wow, i really should have read your comment properly 😂 

Yea so "blended" search seems legit I guess. 

It would be good if the blended search worked with all other types of searches, that way we could still use the same base `search()` and be done with it. 

Otherwise, having a `search_blended()` would be okay i guess, but still have a higher order `search_companies()` that uses `search_blended` under the hood

**Comment by js-stark** [comment]
Sir, how can  I search using blended coz I'm unable to make such a type of API request.
Could you pls help me out with this

**Comment by js-stark** [comment]
How can I make a blended search manually find the API link in the Networks tab
