### ISSUE TITLE
Get all posts by a company

### ISSUE THREAD

**Issue by songsh** [tomquirk/linkedin-api#193]
search_posts  has this function ?

**Comment by abinpaul1** [comment]
Can you pleae elaborate a bit more as to what the issue is.

**Comment by songsh** [comment]
i need crawler  company posts, how can i do this work.  i see get_profile_post, but no get_company_posts,  or search()  function can crawler company posts ?

**Comment by abinpaul1** [comment]
It has not been implemented yet.

**Comment by jfmiraucn** [comment]
Buenos días. Alguno ha encontrado una posible solución para este caso, se los agradezco.

**Comment by Rapid1898-code** [comment]
Hello - is there any solution for that in the meantime?

**Comment by abinpaul1** [comment]
The enpoint is `https://www.linkedin.com/voyager/api/organization/updatesV2`

`GET` url query params: 
companyIdOrUniversalName=1063
count=10
moduleKey=ORGANIZATION_MEMBER_FEED_DESKTOP
paginationToken=657919586-1659009338133-10cf026e19938c8acee2c7c031bf1695
q=companyRelevanceFeed
start=3

**Comment by Rapid1898-code** [comment]
ok thanks - so when i understand this correct this is still currently not available in the linkedin-api module.
And you mean i should use the "normal" API-endpoint form linkedin.
How do you get this informations (Token? companyIdOrUniversalName? etc.)

Also i get an error when putting this eg. in Insomnia for testing the request:
CSRF check failed.

**Comment by abinpaul1** [comment]
Company id is the number part of company URN. Have a look at https://github.com/tomquirk/linkedin-api/blob/14cf87950767705656f0b273a9b99fa9aa9cdd0c/linkedin_api/linkedin.py#L867

Token, I think first time you don't need it. You'll get it in response and then use that for next request. That's mostly how it's used in other endpoints.

You can't use the url directly, as you noted csrf check fails. Maybe add a new function to this library and use that, similar to the one I linked above. So all the authentication, cookie, csrf stuff will be taken care for you.

**Comment by zafercavdar** [comment]
`organization/updatesV2` endpoint returns 500. Is that deprecated?

**Comment by iicey** [comment]
> `organization/updatesV2`端点返回 500。是否已弃用？

params = {
    'companyUniversalName': '40653509',
    'count': '100',
    'moduleKey': 'ORGANIZATION_MEMBER_FEED_DESKTOP',
    'numComments': '0',
    'numLikes': '0',
    'q': 'companyFeedByUniversalName',
    'start': '0',
}
api = Linkedin(
    username=username,
    password=password,
    proxies={
        # "socks5": "127.0.0.1:1080",
        "http": "http://127.0.0.1:1087",
        "https": "https://127.0.0.1:1087"
    }
)
company_infos = api._fetch("/organization/updatesV2", params=params).json()
json.dump(company_infos, open("updatesV2.json", "w"), ensure_ascii=False, indent=2)

**Comment by iicey** [comment]
API：/organization/updatesV2
API：/feed/updates
It seems that I can't get the timestamp

**Comment by tomquirk** [comment]
This should be covered with get_company_updates: https://linkedin-api.readthedocs.io/en/latest/api.html#linkedin_api.Linkedin.get_company_updates

If it's not, pls reopen this issue. Thanks!
