### ISSUE TITLE
slow speed of get_profile and get_profile_contact_info

### ISSUE THREAD

**Issue by drumairali** [tomquirk/linkedin-api#194]
these commands are extremely slow .. for example when we have to explore 1000 profile it may take hours
i did some analysis
each command like 
1    profile = api.get_profile('billy-g')
2    contact_info = api.get_profile_contact_info('billy-g')
3    connections = api.get_profile_connections('1234asc12304')
is taking 10 seconds on average....
how can i make it faster?

**Comment by abinpaul1** [comment]
I believe that has been done purposefully to avoid getting your account banned. There's a `sleep(rand(2,5))` after each request is sent.

See  [here](https://github.com/tomquirk/linkedin-api/blob/20b17418e6fc46e834e500617d06562eaaa48857/linkedin_api/linkedin.py#L30)

If you want to try it out without this, you could clone the repo, comment out all calls to `evade()` and use it. 

Certain methods like `get_profile_connections` do seem to take some time to return the results at times from the server. 

Commenting out evade will help with getting rid of the extra time we `sleep`. However your chances of getting banned increase.

**Comment by drumairali** [comment]
thank you so much for explaining this to me
i really appreciate it

thanks
umair
