### ISSUE TITLE
Return more data for search_people?

### ISSUE THREAD

**Issue by josephtey** [tomquirk/linkedin-api#201]
Hi!

How does search_people() actually work? 

The docs say that it returns 'minimal data only'. Why is this so? 

Am I able to get the function to return more data?

**Comment by abinpaul1** [comment]
It returns a list of profile urns corresponding to the profiles returned from the search. That is what is meant by 'minimal data'. You would then have to fetch more details about the profile by using the `get_profile` method (this takes the urn as argument)

**Comment by abinpaul1** [comment]
Closing for now. Feel free to reopen if your issue has not been clarified.
