### ISSUE TITLE
From today I get an error 404 on the API

### ISSUE THREAD

**Issue by mpizosdim** [tomquirk/linkedin-api#203]
Can anyone validate if this API is working today?

It used to work for me, but I get this error from today when using `linkedin_api.get_profile(profile_url)`:

```
File "/home/dimitris/.local/lib/python3.6/site-packages/linkedin_api/linkedin.py", line 498, in get_profile
    self.logger.info("request failed: {}".format(data["message"]))
KeyError: 'message'
```
And thats because the `self._fetch` of `get_profile` gives back dict `{'status':404}`

I am using `linkedin_api==2.0.0-alpha.5`

**Comment by abinpaul1** [comment]
It seems to be working for me. Please do provide an example to recreate it locally.

**Comment by abinpaul1** [comment]
Feel free to reopen with more details if you still face the issue
