### ISSUE TITLE
 search_jobs() returning only 1000 rows

### ISSUE THREAD

**Issue by diegopmayer** [tomquirk/linkedin-api#204]
### Objective
- Search all opened jobs for the specific **position** in the world

### Issue
- I tried using the `limit=50000` or other value but returned max 1000 rows

### Question
- Can I request more than 1000 rows? if yes, how? case any other suggestion?

### Code:
-----------------------------------------------------------------------------------------------------------------------------

environ = pd.read_csv('.env')
USER_KEY = environ['USER_KEY']
USER_SECRET = environ['USER_SECRET']

api = Linkedin(USER_KEY, USER_SECRET)
de_jobs = api.search_jobs(job_title='"data engineer"', limit=50000, location_name='"world"')

**Comment by diegopmayer** [comment]
Hi @abinpaul1 
Thanks for the answer, so, if I understood, I can't receive more than 1000 rows, right?

**Comment by abinpaul1** [comment]
Yes

**Comment by diegopmayer** [comment]
Ok @abinpaul1, thanks for your return.
