### ISSUE TITLE
Search for companies by geo/region/location?

### ISSUE THREAD

**Issue by bradkyle** [tomquirk/linkedin-api#206]
How should one parameterize the search request to allow for filtering of results, in this case company results, by their respective companyHQGeo, companySize etch. as would be done in regular LinkedIn search?

i.e.

https://www.linkedin.com/voyager/api/search/blended?count=49&filters=List(resultType-%3ECOMPANIES,companyHqGeo-%3E104035573,companySize-%3EE%7CF%7CG%7CH%7CI)&origin=FACETED_SEARCH&q=all&start=0&queryContext=List(spellCorrectionEnabled-%3Etrue)

[returns all companies irrespective of companyHQgeo or companySize]

is not equivalent to the following request on linkedin:

https://www.linkedin.com/search/results/companies/?companyHqGeo=%5B%22104035573%22%5D&origin=GLOBAL_SEARCH_HEADER&sid=x0%3B

Thanks

**Comment by abinpaul1** [comment]
The request goes to `https://www.linkedin.com/voyager/api/search/dash/clusters` endpoint. The companySize is represented as categories( For instance, 11-50 is marked as C, 51-200 is represented as D and onwards). 

The corresponding fetch request looks something like this
```
fetch("https://www.linkedin.com/voyager/api/search/dash/clusters?decorationId=com.linkedin.voyager.dash.deco.search.SearchClusterCollection-132&origin=FACETED_SEARCH&q=all&query=(keywords:cisco,flagshipSearchIntent:SEARCH_SRP,queryParameters:(companyHqGeo:List(102221843),companySize:List(C,D),resultType:List(COMPANIES)),includeFiltersInResponse:false)&start=0", {
  "headers": {
    "accept": "application/vnd.linkedin.normalized+json+2.1",
    "accept-language": "en-US,en;q=0.9,ml;q=0.8",
    "sec-ch-ua": "\"Google Chrome\";v=\"95\", \"Chromium\";v=\"95\", \";Not A Brand\";v=\"99\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"macOS\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "x-li-lang": "en_US",
    "x-li-page-instance": "urn:li:page:d_flagship3_search_srp_companies;x4llj2qbS9OTdzjbZcNlvg==",
    "x-li-track": "{\"clientVersion\":\"1.10.594\",\"mpVersion\":\"1.10.594\",\"osName\":\"web\",\"timezoneOffset\":5.5,\"timezone\":\"Asia/Calcutta\",\"deviceFormFactor\":\"DESKTOP\",\"mpName\":\"voyager-web\",\"displayDensity\":2.5,\"displayWidth\":4480,\"displayHeight\":2800}",
    "x-restli-protocol-version": "2.0.0"
  },
  "referrer": "https://www.linkedin.com/search/results/companies/?companySize=%5B%22C%22%2C%22D%22%5D&keywords=cisco&origin=FACETED_SEARCH&sid=T7b",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "GET",
  "mode": "cors",
  "credentials": "include"
});
```

**Comment by bradkyle** [comment]
Thanks for your quick reply.
Yea, so I've tried doing this before i.e. just replicating the request sent by linkedin frontend, just returns an html page...
Is there any way that I could succinctly get the data from the voyager api in json while filtering by geo?
Thanks

**Comment by abinpaul1** [comment]
The fetch request I mentioned above returns json. AFAIK all requests made to `www.linkedin.com/voyager/api/` returns json results.

**Comment by bradkyle** [comment]
Apologies, there was an error in the implementation of the fetch function ported into python. This resolved the problem.
Thank you, have an awesome day.

**Comment by BernardoGO** [comment]
@bradkyle 
Have you succeeded on implementing this? Would you mind sharing the solution?
My requests are returning 400.

`            default_params = {
                "decorationId": "com.linkedin.voyager.dash.deco.search.SearchClusterCollection-135",
                "origin": "FACETED_SEARCH",
                "q": "all",
                "query":f"(keywords:'{keywords}',flagshipSearchIntent:SEARCH_SRP,queryParameters:(companyHqGeo:List(106057199),resultType:List(COMPANIES)),includeFiltersInResponse:false)",
                "start": "0"

            }
            
            res = self._fetch(
                f"/search/dash/clusters?{urlencode(default_params, safe='(),')}",
                headers={"accept": "application/vnd.linkedin.normalized+json+2.1"},
            )
            data = res.json()`
