### ISSUE TITLE
"No module named linkedin_api" when running example code

### ISSUE THREAD

**Issue by GabrielxCS** [tomquirk/linkedin-api#226]
**Before you say anything, yes i installed it, it shows up when i run** pip list\

i have the exact same lines of code the example has so its not a syntax issue, is this project deprecated? or something?

**Comment by abinpaul1** [comment]
Hi @GabrielxCS ,
The project is not deprecated. It seems it might be a mismatch between the `python` for which you have installed the package (this could happen if you have multiple python installed. I cant help without more details about your setup.
I would recommend the following steps:
```
python3 -m venv linkedin_env
source linkedin_env/bin/activate
pip install install git+https://github.com/tomquirk/linkedin-api.git
```
and then try running the example code from the same shell.

**Comment by abinpaul1** [comment]
Closing for now. Feel free to reopen if issue persists.

**Comment by egor-ryashin** [comment]
I've got the same:
```
    from linkedin_api import Linkedin
ModuleNotFoundError: No module named 'linkedin_api'
``

**Comment by egor-ryashin** [comment]
Also, I noticed that `pip` shows a different name (`dash` not `underscore`):
```
pip freeze
linkedin-api==2.3.0
```

**Comment by egor-ryashin** [comment]
Never mind, it's a different version of `pip` intervened. I installed with `python -m pip linkedin-api` and it worked.
