### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by tbressers** [tomquirk/linkedin-api#237]
The last one dated October 2020.... 

Best regards - Thijs

**Comment by tomquirk** [comment]
@tbressers @abinpaul1 yep lets do it.

**Comment by FFFF-0000h** [comment]
Great stuff 🥳.
V2

**Comment by tbressers** [comment]
Hi Tom, anything holding us from releasing 2.0? I think it would make a huge improvement over the last one!
