### ISSUE TITLE
Error when requesting posts of a profile?

### ISSUE THREAD

**Issue by Rapid1898-code** [tomquirk/linkedin-api#247]
Hello - i want to get the posts of a profile using this code:

```
from linkedin_api import Linkedin
api = Linkedin(LINKEDIN_EMAIL, LINKEDIN_PW)
erg = api.get_profile_posts('billy-g')
```
But unfortunately i get this error:

```
$ python LinkedinProfile.py
Traceback (most recent call last):
  File "LinkedinProfile.py", line 18, in <module>
    erg = api.get_profile_posts('billy-g')
AttributeError: 'Linkedin' object has no attribute 'get_profile_posts'
```

How can i get the posts of a profile?

**Comment by abinpaul1** [comment]
Please use the latest code taken from this repo- Refer Readme. The pypi release version might lacks newly added functions.

**Comment by Rapid1898-code** [comment]
Hello - thanks a lot - works great as you said with this installation-method:

`pip3 install git+https://github.com/tomquirk/linkedin-api.git`
