### ISSUE TITLE
get_post_comments returns 500

### ISSUE THREAD

**Issue by ubervincent** [tomquirk/linkedin-api#258]
Here's the code I have written
`comments = api.get_post_comments('urn:li:activity:6983447783852683264')`

Here's the error message I got:
`INFO:linkedin_api.linkedin:request failed: 500`

I wonder if anyone has some issue with that?

**Comment by ubervincent** [comment]
> Can you please try : `comments = api.get_post_comments('6983447783852683264')`

This works!

**Comment by abinpaul1** [comment]
Cool! Closing the issue for now.
