### ISSUE TITLE
No params in get_conversations

### ISSUE THREAD

**Issue by zzac** [tomquirk/linkedin-api#269]
I managed to add a "count" param into the get_conversations function but I can't find a way to get unread conversations and conversations that contain a specific term for instance. Moreover, the "start" param changes the "paging" "start" value in the JSON response but doesn't affect the conversations I get.

I know that LinkedIn messaging page uses the "/voyagerMessagingGraphQL/graphql" endpoint rather than "/messaging/conversations" so that could maybe be a solution ?

**Comment by manuelrech** [comment]
hello, how did you solved this??
