### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by ahsentekd** [tomquirk/linkedin-api#270]
error on while getting profile skills on some profiles.
`    profile["skills"] = self.get_profile_skills(public_id=public_id, urn_id=urn_id)
`

**Comment by Merlin1A** [comment]
See my response to issue #272. If that does not help, please post some more details so we can help.

**Comment by ahsentekdemir** [comment]
thx bud, do u have any strategy for get no banning or handle it?

**Comment by Merlin1A** [comment]
I'm currently working through this code for my own project, so I do not fully understand this whole code base yet. 

If your ban question has to do with this error, can you post more details? Is the random time evade not working for you? 

If your 'evading ban' question is not related to this issue, please post a new issue with some details, and I'll help.

**Comment by tomquirk** [comment]
JSONDecodeError just means that your request didn't return JSON, which typically means that some LinkedIn rate-limiting has kicked in, or your account has been restricted.
