### ISSUE TITLE
Installation and other issues

### ISSUE THREAD

**Issue by Ulixestoitaca** [tomquirk/linkedin-api#28]
Hello,
I am using Pycharm and attempting to install your package.
First of all "pip install linkedin-api" raise an error, "no such file or directory README.md".

Anyway I have installed components as per travi.yml.

I run tests pipenv run python -m pytest tests -s and got 5 tests failed, the main of them is "ERROR at setup of test_get_profile_connections", it seems I cannot get authenticated. Login/psw are absolutely right and I am connecting by the same IP I normally use for logging linkedin.

I modified .env.example to .env and this is its content
LINKEDIN_USERNAME="francescovergi@hotmail.com"
LINKEDIN_PASSWORD="**************"
TEST_PROFILE_ID="ACoAABQ11fIBQLGQbB1V1XPBZJsRwfK5r1U2Rzt"
TEST_CONVERSATION_ID="6419123050114375168"

------>>> Pycharm raise an "unresolved reference" for linkedin.api.* <<<-----

Could someone kindly help me?

**Comment by tomquirk** [comment]
Hey @Ulixestoitaca , thanks for raising this.

Installing via pip is indeed broken, will need to fix that.

The test config you will need to update yourself - those example values won't work

**Comment by tomquirk** [comment]
fixed pypi as of 1.0.1. You'll porbably need to uninstall and clear your pip cache
