### ISSUE TITLE
CSRF check failed

### ISSUE THREAD

**Issue by Ulixestoitaca** [tomquirk/linkedin-api#29]
Hello,

I have logged to Linkedin but Voyger API raise a CSRF error, for this reason (I think) I am not able to extract data. 
Consider that I have just installed the package so I have not run big scraping.

**Comment by tomquirk** [comment]
did you end up fixing this @Ulixestoitaca ?

**Comment by quesurifn** [comment]
@tomquirk I have a similar issue. I'm converting your library to node (I'll give you all the credit in the world, you can even publish it; I just need it).

**Comment by chennien** [comment]
Same error when creating a new profile in a different language in 2022, please fix.

**Comment by abinpaul1** [comment]
@chennien I am a bit confused about what you mean by fix. Are you facing an issue while using this python library. If so please do provide the code you tried and the error message as well
