### ISSUE TITLE
Considerations

### ISSUE THREAD

**Issue by damianoporta** [tomquirk/linkedin-api#299]
Hello everybody and thank you @tomquirk for this awesome library.

I am opening this issue just to make few considerations about the usage of this library.
As you may know Linkedin tracks many things: logins, time one page, clicks on elements, basically everything.
Just analyzing the headers of their requests i see for example **x-li-page-instance**, **searchId** and many others control headers.

I wonder how this library can longer works because it is highly notable to me. I am saying that because it just sends the requests to get data from Voyager APIs, without also sending fake tracks calls etc.

I suppose Linkedin tolerates this usage(within limits), but the feeling is that we are at the mercy of their decisions because our requests clearly come from bots.

Do you think they are useless considerations or should we combine the use of this library with selenium to simulate navigation?
Thank you

**Comment by tomquirk** [comment]
@damianoporta great ideas! Going to close this issue for now, but please join the Discord where we can discuss further: https://discord.com/invite/9w5c6xzm
