### ISSUE TITLE
Send message to connected people

### ISSUE THREAD

**Issue by Ulixestoitaca** [tomquirk/linkedin-api#30]
Hello,

for what I see it is possible to send messages only to people with wich a conversation has started already.
I wonder if and how it would be possible to send a message to connected people even if no conversation has started.

Thank you!

**Comment by tomquirk** [comment]
as of v1.0.1, you can! (Sorry im not following semver, im going to fix up all the releases/versions soon lol)

**Comment by Ulixestoitaca** [comment]
ok I succeded to send msg to people connected.
Linkedin is going to deprecate v1, will this project survive?
