### ISSUE TITLE
My LinkedIn account got restricted.

### ISSUE THREAD

**Issue by hemangjoshi37a** [tomquirk/linkedin-api#307]
Please let me know what to do because my account has got restricted after using this api. please let me know if anyone has faced similar isseus and how to solve this .

**Comment by sl-ll** [comment]
Registered four accounts, three of them used this api last few days and the last one did not.
Those was used are restricted today.
For all accounts the initial run used dedicated cookies_dir and runs was not started in parallel for all accounts

**Comment by chrishubert** [comment]
hmmmm, that's a bit scary – anyone else had faced this?

**Comment by t-khush** [comment]
Any updates/fix?

**Comment by hemangjoshi37a** [comment]
my restriction was removed after certain hours but it does not seem very legit to use this library with unlimited access of linkedin api, also you might get permanently banned so be careful with what you do here.

**Comment by CrazyHorse117** [comment]
After a few days of testing and google searching it seems there are two main methods to avoid this.
1) Don't send too many requests too quickly. The evade code slows this down already
2) The number of requests sent in 24 hours

Point 2 has blocked my accounts for a short period and then they restore your access quickly. 

But for each account that has its access restored the API no longer works and I just get errors

**Comment by tomquirk** [comment]
@hemangjoshi37a @chrishubert @t-khush @CrazyHorse117 @sl-ll come join the Discord where we can discuss further: https://discord.com/invite/9w5c6xzm

**Comment by tomquirk** [comment]
@capybarahero sorry about that. Try this one! https://discord.com/invite/hdd48NEB37
