### ISSUE TITLE
get_profile_connections() always returns my connections.

### ISSUE THREAD

**Issue by ghazalrafiei** [tomquirk/linkedin-api#311]
I am trying to get people's connections list but whatever I send to `get_profile_connection()` as an argument the output is the list of MY connections!

**Comment by Malekai-git** [comment]
Hope you were able to get this solved! I sadly am having issues with this get_profile_connections as well, except whenever I try it it returns an empty list. Example:

connections = api.get_profile_connections('urn:li:fs_profile:ACoAAAylSRIBXNFRGjmGfTQsZZL04N8Sf_IyVao')
print(connections) 
[] 

If anyone has recommendations / tips to make this not return an empty list and actual return the connections, that'd be amazing!

**Comment by Hakurei-git** [comment]
> Hope you were able to get this solved! I sadly am having issues with this get_profile_connections as well, except whenever I try it it returns an empty list. Example:
> 
> connections = api.get_profile_connections('urn:li:fs_profile:ACoAAAylSRIBXNFRGjmGfTQsZZL04N8Sf_IyVao') print(connections) []
> 
> If anyone has recommendations / tips to make this not return an empty list and actual return the connections, that'd be amazing!

Hello, you can analyze the API of LinkedIn website to obtain data, and then write a method. It's very simple to implement.

**Comment by tomquirk** [comment]
@Malekai-git see https://github.com/tomquirk/linkedin-api/issues/407

This is fixed on `main` and will be released on pyPi shortly. Thanks!
