### ISSUE TITLE
Any proxy recommandations ? 

### ISSUE THREAD

**Issue by michael-quickmail** [tomquirk/linkedin-api#321]
Hey there, thanks for this library ! 

It seems that when running it on a cloud provider -- or any home made Linkedin automation tool for that matter -- it gets easily banned from Linkedin.

Do you have any recommandations of rotational/mobile/residential proxies that support targeting Linkedin ? 
Ideally something that has been used successfully in production ?

I've tried multiple providers but so far their IPs were already banned, or the provider itself was blocking Linkedin as it is against their rules.

**Comment by quantryx** [comment]
I use webshare.io

**Comment by tomquirk** [comment]
@michael-quickmail I use and recommend BrightData, especially for residential proxies: https://get.brightdata.com/v0qdnffggqeb (disclaimer: this is an affiliate link)

**Comment by Cazforshort** [comment]
> @michael-quickmail I use and recommend BrightData, especially for residential proxies: https://get.brightdata.com/v0qdnffggqeb (disclaimer: this is an affiliate link)

With this api? I don't see how they would work together?
