### ISSUE TITLE
add_connection() is not working.

### ISSUE THREAD

**Issue by yuvraj123-verma** [tomquirk/linkedin-api#324]
when i try to send invitation to any linkedin user. this add_connection() api not working. its return false but not sending request.

**Comment by Njoselson** [comment]
These tests are failing:
```
FAILED tests/test_linkedin_api_requests.py::test_accept_invitation - assert False
FAILED tests/test_linkedin_api_requests.py::test_reject_invitation - assert False
```

**Comment by tomquirk** [comment]
https://github.com/tomquirk/linkedin-api/pull/453
