### ISSUE TITLE
In this function Linkedin(email, password) getting linkedin_api.challenge.exception issue on the server 

### ISSUE THREAD

**Issue by s-python-code** [tomquirk/linkedin-api#329]
My one linkedin credential is working on EC2 server and for other linkedin credentials getting exception challenge.
And when I use my credentials it works for 2-3 weeks without any issue, but after some time gives a challenge exception then again after 1 week works API.

**Comment by jidelberger** [comment]
Got the same problem on pythonanywhere.

**Comment by tomquirk** [comment]
@s-python-code this is unavoidable unforunately. It's an exercise for the reader to work around LinkedIn's limitations, but be wary of their Terms of Service.

Come join the Discord to discuss further: https://discord.com/invite/9w5c6xzm

cc @jidelberger
