### ISSUE TITLE
search_people with regions fails

### ISSUE THREAD

**Issue by Ulixestoitaca** [tomquirk/linkedin-api#33]
I run the code listed in the examples (and other attempts)

results = linkedin.search_people(
  keywords='software,lol',
  connection_of='AC000120303',
  network_depth='F',
  regions=[4909],
  industries=[29, 1]
)

but I got this error 
*****
in search_people
    filters.append(f'geoRegion->{"|".join(regions)}')
TypeError: sequence item 0: expected str instance, int found
******

**Comment by tomquirk** [comment]
Sorry about that @Ulixestoitaca , the docs are likeley out of date. I would try making those values strings, i.e.

```python
...
regions=['4909']
```

**Comment by Ulixestoitaca** [comment]
Hello,
I am trying to get results by city and/or country but it seems something it is not working.
I tried to apply these codes https://developer.linkedin.com/docs/reference/geography-codes converting in striings but API doesn't give any result back.
Do you have any suggestion?
I see you use this query
        res = self._fetch(
            f"/search/blended?{toqs(default_params)}",
            headers={"accept": "application/vnd.linkedin.normalized+json+2.1"},
        )
but I am not able to find any documentation for search/blended in api documentation at https://linkedin.api-docs.io/v1.0/search/RWHmniwaq7msAoZTM

**Comment by tomquirk** [comment]
WOAH! Dude, where did you find those last docs?? That's amazing.

This project has been built from reverse-engineering linkedin.com - the blended search is simply what they use in the UI! But I had no idea Voyager was actually documented.

Regarding the geocodes, that list is also great! however I haven't come across those in the wild - only numbers. If you do a search with a region on linkedin.com, and look at the request, you'll see its generally a 4-digit code

**Comment by Ulixestoitaca** [comment]
but where exactly you run this research on linkedin?? I am not able to see api output on browser because I get constantly a crif error.
Another question: are you able to run queries by city in some way?

**Comment by tomquirk** [comment]
have a read of the README - I outline the process.

Cities, yes. It's just another geocode. Do a search on Linkedin and observe the Network tab of your dev tools. For example, if I search `software developer` in Sydney, Australia, the query they construct looks like
```
count: 10
filters: List(geoRegion->au:4910,resultType->PEOPLE)
keywords: software developer
origin: FACETED_SEARCH
q: all
queryContext: List(spellCorrectionEnabled->true,relatedSearchesEnabled->true,kcardTypes->PROFILE|COMPANY)
start: 0
```
Notice geoRegion of au:4910

**Comment by Ulixestoitaca** [comment]
very smart!

**Comment by Ulixestoitaca** [comment]
anyway I am getting this error

    for i in range(len(data["data"]["elements"])):
KeyError: 'data'

with au:4910 and other codes. It seems is not retriving results

**Comment by tomquirk** [comment]
Confirmed bug!

**Comment by Ulixestoitaca** [comment]
Could you just explain this to me

you send params from serch_people to search
def search(self, params, limit=None, results=[]):

but I am not able to understand where params is called in order to send the query to APIs.
You call f"/search/blended?{toqs(default_params)}" but default_params does not contain params

**Comment by tomquirk** [comment]
line 85 

```python
default_params.update(params)
```

**Comment by Ulixestoitaca** [comment]
ah I have not default_params.update(params) in my code

**Comment by Ulixestoitaca** [comment]
I have noticed that running a query on linkedin the voyager call made by network is 

https://www.linkedin.com/voyager/api/search/filters?filters=List(geoRegion->au:4900,resultType->PEOPLE)&q=universalAll&queryContext=List(spellCorrectionEnabled->true,relatedSearchesEnabled->true,kcardTypes->PROFILE|COMPANY)

in our case we use https://www.linkedin.com/voyager/api/search/blended

I have tryed to replace "filters" to "blended" but no success.

**Comment by tomquirk** [comment]
Ah, Yea I recently updated to the blended search. I think blended search means that you're expecting results for more than one type of entity (i.e. if I search "software" I'll get people, jobs companies etc.). Keep playing with it, if I have a chance I'll take a look

**Comment by tomquirk** [comment]
fixed and tested 👍

**Comment by Ulixestoitaca** [comment]
Hello,

I've tried

results = api.search_people(
  network_depth='O',
  keywords='developer',
  regions= 'au:4910', limit=30
)

yes now it doesn't rise any errors but profiles are not related to the request region but ordered by distance.

Furthermore I wonder how and if it woould be possible to search by city and by postal code
