### ISSUE TITLE
Connection Error Occurs When Sending Message with Invitation

### ISSUE THREAD

**Issue by MathieuDelmarre** [tomquirk/linkedin-api#353]
Hello,

I'm encountering an issue when sending a connection that includes a message. The response I get is:

css

{
    "data": {
        "code": "CUSTOM_INVITE_LIMIT_REACHED",
        "status": 429
    }
}

However, when I omit the message from the invitation, it gets sent without any issues.

Can you please assist with this?

**Comment by ranjan-2209** [comment]
This may be default behaviour by LinkedIn. You may solve this problem by buying Premium subscription
