### ISSUE TITLE
get_profile only returns the first few work experiences 

### ISSUE THREAD

**Issue by dyerrington** [tomquirk/linkedin-api#388]
```python
api = Linkedin(**opts)
# GET a profile
profile = api.get_profile('davidyerrington')
```
The response only grabs the first 4 or so work histories from me.  I also tried updating `get_profile` to include pagination parameters like I've seen in other methods in the codebase but the Voyager API seems to not care in this instance.  Is it possible to get complete work history for me?

Thanks!

**Comment by Prii-y** [comment]
Heyy @dyerrington were u able to find a solution for this?
Thanks!
