### ISSUE TITLE
Searching for people currently at a particular company yields no correct results

### ISSUE THREAD

**Issue by GutHibbb** [tomquirk/linkedin-api#39]
Using the `search_people(current_company=['1441'])` function is meant to list all employees at company 1441 (Google), however it yields no _correct_ results. It generates a long list of people that do not work at the company in question, looks similar to a 'people you may know' list.

The script generates the following URL:

`/voyager/api/search/blended?count=49&filters=List(resultType->PEOPLE,currentCompany->1441)&origin=GLOBAL_SEARCH_HEADER&q=all&start=0&queryContext=List(spellCorrectionEnabled->true,relatedSearchesEnabled->true,kcardTypes->PROFILE|COMPANY)`

When I attempt the same search on desktop it generates the following url in the source code:

`/voyager/api/search/blended?count=10&filters=List(currentCompany->1441|791962|2374003|18950635|16140|10440912,resultType->PEOPLE)&origin=OTHER&q=all&queryContext=List(spellCorrectionEnabled->true,relatedSearchesEnabled->true,kcardTypes->PROFILE|COMPANY|JOB_TITLE)&start=0`

I notice the differences with respect to 'origin' and count. Changing the code so that these match does not seem to help.

**Comment by 1138559250** [comment]
Hi, I encountered the same problem, search_people(current_company=['1441']) returned incorrect results and generated a long list of irrelevant people, did you solve this problem?

**Comment by tomquirk** [comment]
Looks to be working now. Closing!

<img width="481" alt="Screenshot 2024-09-02 at 9 59 34 PM" src="https://github.com/user-attachments/assets/69c4d953-dba0-446c-a2ab-39d0345c6293">
