### ISSUE TITLE
advice to avoid CHALLENGE

### ISSUE THREAD

**Issue by Eitol** [tomquirk/linkedin-api#392]
To prevent the challenge from being sent to me, I used Firefox cookies:

- I logged in with Firefox
- Then I extract the cookies with browser_cookie3

```python
cookiejar_simple = browser_cookie3.firefox(domain_name='.linkedin.com')
cookiejar = requests.cookies.RequestsCookieJar()
for cookie in cookiejar_simple:
    cookiejar.set_cookie(cookie)        
api = Linkedin('', '', cookies=cookiejar)
```

I leave it to you as advice because it has helped me.

**Comment by selllikesybok** [comment]
Worked for me, thanks!

Important context for anyone else who may not realize: Chrome and possibly all Chromium browsers currently implement a difficult-to-circumvent (at least on Windows) lock on the cookies file. Firefox does not. You can go down a whole set of rabbit holes trying to figure that out, or just use a non-Chromium browser.

**Comment by KISHAN8888** [comment]
this method is not working throwing same challange error.  Any other recommendations?

**Comment by yash85763** [comment]
@Eitol How did you extract the cookies, I am trying to find a way to extract cookies and not able to find it, I am using Firefox browser!

**Comment by cedibb** [comment]
> @Eitol How did you extract the cookies, I am trying to find a way to extract cookies and not able to find it, I am using Firefox browser!

This is what I usually use. Paste it in your dev console:

`function getLinkedinSessionCookie() {
  const cookieName = "JSESSIONID=";
  const cookies = document.cookie.split(";").map((cookie) => cookie.trim());

  const cookie = cookies.find((cookie) => cookie.startsWith(cookieName));

  if (!cookie) {
    return "";
  }

  const cookieValue = cookie.substring(cookieName.length);

  if (cookieValue.startsWith('"') && cookieValue.endsWith('"')) {
    return cookieValue.slice(1, -1);
  }

  return cookieValue;
}

getLinkedinSessionCookie()
`

**Comment by cedibb** [comment]
This is how I do it. Just paste into your browser's dev console:

```
function getLinkedinSessionCookie() {
  const cookieName = "JSESSIONID=";
  const cookies = document.cookie.split(";").map((cookie) => cookie.trim());

  const cookie = cookies.find((cookie) => cookie.startsWith(cookieName));

  if (!cookie) {
    return "";
  }

  const cookieValue = cookie.substring(cookieName.length);

  if (cookieValue.startsWith('"') && cookieValue.endsWith('"')) {
    return cookieValue.slice(1, -1);
  }

  return cookieValue;
}

getLinkedinSessionCookie()

```

**Comment by cedibb** [comment]
> @Eitol How did you extract the cookies, I am trying to find a way to extract cookies and not able to find it, I am using Firefox browser!

This is how I do it. Just paste into your browser's dev console:

```
function getLinkedinSessionCookie() {
  const cookieName = "JSESSIONID=";
  const cookies = document.cookie.split(";").map((cookie) => cookie.trim());

  const cookie = cookies.find((cookie) => cookie.startsWith(cookieName));

  if (!cookie) {
    return "";
  }

  const cookieValue = cookie.substring(cookieName.length);

  if (cookieValue.startsWith('"') && cookieValue.endsWith('"')) {
    return cookieValue.slice(1, -1);
  }

  return cookieValue;
}

getLinkedinSessionCookie()

```

**Comment by zarlicho** [comment]
> To prevent the challenge from being sent to me, I used Firefox cookies:
> 
> * I logged in with Firefox
> * Then I extract the cookies with browser_cookie3
> 
> ```python
> cookiejar_simple = browser_cookie3.firefox(domain_name='.linkedin.com')
> cookiejar = requests.cookies.RequestsCookieJar()
> for cookie in cookiejar_simple:
>     cookiejar.set_cookie(cookie)        
> api = Linkedin('', '', cookies=cookiejar)
> ```
> 
> I leave it to you as advice because it has helped me.

i got this error requests.cookies.CookieConflictError: There are multiple cookies with name, 'JSESSIONID' when getin firefox cookies with browser_cookies3

**Comment by yassinemab** [comment]
> > To prevent the challenge from being sent to me, I used Firefox cookies:
> > 
> > * I logged in with Firefox
> > * Then I extract the cookies with browser_cookie3
> > 
> > ```python
> > cookiejar_simple = browser_cookie3.firefox(domain_name='.linkedin.com')
> > cookiejar = requests.cookies.RequestsCookieJar()
> > for cookie in cookiejar_simple:
> >     cookiejar.set_cookie(cookie)        
> > api = Linkedin('', '', cookies=cookiejar)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I leave it to you as advice because it has helped me.
> 
> i got this error requests.cookies.CookieConflictError: There are multiple cookies with name, 'JSESSIONID' when getin firefox cookies with browser_cookies3

I'm currently facing this issue. Did you manage to fix it?

**Comment by kqvanity** [comment]
@zarlicho 
I think i've resolved this issue by prefixng the domain with www `www.linkedin.com`

If someone has multiple profiles at firefox, then you'd probably need to take a look at [this](https://github.com/borisbabic/browser_cookie3/issues/211#issuecomment-2443632370) as well
