### ISSUE TITLE
Is there any way to find linkedin account using email?

### ISSUE THREAD

**Issue by brestok-1** [tomquirk/linkedin-api#398]
I have connected OpenID Connect. So, after auth, I get an email and I need to find person using this email.

**Comment by tomquirk** [comment]
Hey @brestok-1 , this isn't possible out of the box. But, you could try to create a search query based on the email and find the person that way. For example, if the email was `bill.gates@gmail.com`, you could split the email on the `.` and do a people search for `bill gates`. Obviously there's limitations to this. Best of luck!
