### ISSUE TITLE
Possible to Get Public Profile without logIn with linkedIn

### ISSUE THREAD

**Issue by Zaeem6100** [tomquirk/linkedin-api#406]
I Need to fetch the users public profile using the API is there any way to fetch it without Auth to LinkedIn. Because in EC2 ubuntu server i cant resolve the challanger errors.

**Comment by tomquirk** [comment]
@Zaeem6100 I tried this, and it doesn't look like it's possible.

**Comment by Zaeem6100** [comment]
Resolved that issue

**Comment by Poyu781** [comment]
Hello @Zaeem6100 
Can you share how you resolved this issue? Thank you!
