### ISSUE TITLE
How to get the job link and company urn?

### ISSUE THREAD

**Issue by Dhruvoza2512** [tomquirk/linkedin-api#412]
I am trying to create a spreadsheet that keeps on updating as and when new jobs are posted. I used the search_jobs to search for all the jobs with specific keywords, but I am unable to search for the company and get the link from the retrieved results. This is how the results from search job look like:

{'trackingUrn': 'urn:li:jobPosting:3994694371',
  'repostedJob': False,
  'title': 'Experienced Trader',
  '$recipeTypes': ['com.linkedin.deco.recipe.anonymous.Anon1578943416'],
  'posterId': '484502795',
  '$type': 'com.linkedin.voyager.dash.jobs.JobPosting',
  'contentSource': 'JOBS_PREMIUM_OFFLINE',
  'entityUrn': 'urn:li:fsd_jobPosting:3994694371'}
  
  1. How do I search for the company from this information?
  2. How do I get the job link?
  3. How do I get all the first connections working in this company?

**Comment by gustavotrapp** [comment]
Hey man you marked this as complete, how did you do it, I have the same problem but for `urn:li:fs_position` I want to get the urn for the company after a search_people
