### ISSUE TITLE
Got warning from LinkedIn for automation tools

### ISSUE THREAD

**Issue by Dhruvoza2512** [tomquirk/linkedin-api#414]
Is there any way you can bypass getting caught for sending connection requests through the API? 

I have put a sleep line for 10 minutes after sending one connection to not face this. Does anyone have any other walk around?

**Comment by fbuenohernandez** [comment]
@Dhruvoza2512 did you get banned?

**Comment by tomquirk** [comment]
Working around this is an exercise for the reader. Not much we can do about it unfortunately!
