### ISSUE TITLE
Search people function stopped working

### ISSUE THREAD

**Issue by coreand** [tomquirk/linkedin-api#42]
I started getting this error:
```
File "C:\Users\Andrew\Documents\venv\lib\site-packages\linkedin_api\linkedin.py", line 158, in search_people
    data = self.search(params, limit=limit)
  File "C:\Users\Andrew\Documents\venv\lib\site-packages\linkedin_api\linkedin.py", line 91, in search
    for i in range(len(data["data"]["elements"])):
KeyError: 'data'
```
I added these checks before the loop in your library:
```
if data:
   if "data" in data:
```
It solved the error but search yields 0 results. Seems like LinkedIn stopped returning results by this endpoint.

During the past several days everything worked fine. I currently tried to authorize with different accounts and run code on several machines (Windows and Linux) with different IPs but the issue still persists

**Comment by coreand** [comment]
It suddenly started to work again without me doing anything)

**Comment by coreand** [comment]
It stopped working for me again( I'm getting 0 results or some random amount of the same profiles like 15, 20, 50 profiles

**Comment by tomquirk** [comment]
We just had a contribution that might fix your issue @coreand  - would you mind giving it a test again to confirm if you're still having the issue?

**Comment by tomquirk** [comment]
@coreand are you still having problems? I'm having no issues at the moment. If you are, give me an example of a query you think should be working and I'll take a look

**Comment by tatanfort** [comment]
I'm having the same problem... Have you found a way to fix it by any chance?
