### ISSUE TITLE
Issues with installing and listing wrong version

### ISSUE THREAD

**Issue by afk-procrastinator** [tomquirk/linkedin-api#426]
I'm running into a weird issue where installing via pip (`pip install linkedin-api`) results in this error: 

```
Collecting linkedin-api
  Using cached linkedin_api-2.2.1-py3-none-any.whl.metadata (14 kB)
	# Reqs install
ERROR: For req: linkedin-api. Invalid script entry point: <ExportEntry lint = black:None []> - A callable suffix is required. Cf https://packaging.python.org/specifications/entry-points/#use-for-scripts for more information.
```

Happens when installing via a requirements.txt file or via the terminal. Forcing version 2.0.2 or 2.2.0 (`linkedin-api==2.2.0`) solves the issue — must be something with the versioning?

**Comment by tomquirk** [comment]
Hey @afk-procrastinator sorry about this. I've just released `v2.3.0` which should fix it. Can you try again? Please reopen if it's still broken.
