### ISSUE TITLE
Get Profile not working

### ISSUE THREAD

**Issue by FrancescoBrigo** [tomquirk/linkedin-api#43]
Suddenly the get_people function stopped working, no challenge on the profile and no problem on accessing the account on the browser.

No error is returned.

Maybe a new endpoint?

**Comment by tomquirk** [comment]
Just ran the tests, seems to be working for me. Double checked on linkedin.com and its the same endpoint as well. Maybe log some stuff out in the sourcecode and see if anything is coming back in the response for you?

**Comment by FrancescoBrigo** [comment]
Well I've checked and it was entirely my fault (misreading a file with the profile ids), sorry for the inconvenience and thanks anyway for the answer!
