### ISSUE TITLE
add_connection no longer works: 301-Ressource moved

### ISSUE THREAD

**Issue by BirT356** [tomquirk/linkedin-api#448]
Since yesterday, endpoint for add connection seems to be still there, but the `  "invitee": {"com.linkedin.voyager.growth.invitation.InviteeProfile": {"profileId": <profile_urn_id>}},`
seems to throw an error:  with the code 301 - Ressource Moved.

Where is actually this endpoint on the browser? I can't find it anywhere. The one in the browser (voyager-relationship endpoint ) always invalidates the client which is really annoying. 

Orginal code:
`tracking_id = generate_trackingId()
        payload = {
            "trackingId": tracking_id,
            "message": message,
            "invitations": [],
            "excludeInvitations": [],
            "invitee": {"com.linkedin.voyager.growth.invitation.InviteeProfile": {"profileId": profile_urn_id}},
        }
        res = self._post(
            "/growth/normInvitations",
            data=json.dumps(payload),
            headers={"accept": "application/vnd.linkedin.normalized+json+2.1"},
        )`

**Comment by Alegrossi2001** [comment]
Same happening here

**Comment by yash-exela** [comment]
I tried to debug also but could not found a way. On website I couldn't find any similiar api that they are using behind the scene when connection request is sent.

So, I tried to mimic add_connection method by using _post in same class (Linkedin class) and that is giving {'data': {'status': 422}, 'included': []} as a res.json() output.

Here's code:
import random
import base64

def generate_trackingId() -> str:
    """Generates and returns a random trackingId

    :return: Random trackingId string
    :rtype: str
    """
    random_int_array = [random.randrange(256) for _ in range(16)]
    rand_byte_array = bytearray(random_int_array)
    return str(base64.b64encode(rand_byte_array))[2:-1]


trackingId = generate_trackingId()
payload = {
    "trackingId": trackingId,
    "message": None,
    "invitations": [],
    "excludeInvitations": [],
    "invitee": {
        "com.linkedin.voyager.growth.invitation.InviteeProfile": {
            "profileId": <SOME URN ID>
        }
    },
}

api = Linkedin(link_username, link_password, cookies=cookie_jar)

res = api._post(
    "/growth/normInvitations",
    data=json.dumps(payload),
    headers={"accept": "application/vnd.linkedin.normalized+json+2.1"},
)

print(res.json())


Someone, please look into it and find a way through it.

**Comment by dahani9091** [comment]
Sam happening to me; please lets collaborate to solve this issue!

**Comment by yashdharme** [comment]
I have resolved this issue and tested it but it is without message as of now. I would like to contribute. How can I?
