### ISSUE TITLE
Sponser link doesnt work

### ISSUE THREAD

**Issue by DeanVanGreunen** [tomquirk/linkedin-api#458]
The sponsorship link in the main README doesn't work, I would like to be a sponsor, as this would be a vital feature in out product

**Comment by tomquirk** [comment]
Hi @DeanVanGreunen , thanks for your interest in becoming a sponsor! This is the correct link: https://github.com/sponsors/tomquirk

I've fixed the link in the README too :)

Reach out to me on LinkedIn if you'd like to discuss more.
