### ISSUE TITLE
get_conversations

### ISSUE THREAD

**Issue by AchatY** [tomquirk/linkedin-api#46]
get_conversations return only the 20 first results .. 
I saw the documentation in https://linkedin.api-docs.io/v1.0/messaging/C5NLMQokSqdLZbcr8
and I see that there is an integer param  createdBefore .
But that doesn't work .. ?
Can I have an example of something that work ? 

Thank you

**Comment by tomquirk** [comment]
nice find 👍 It's not implemented but would be very easy to do so! I'd be happy to walk you through necessary steps if you'd like to contribute

**Comment by AchatY** [comment]
Hello,
Here's how I managed to do it and it works very well


    def get_conversations(self, createdBedore=None):
        """
        Return list of conversations the user is in.
        """
        params = {"keyVersion": "LEGACY_INBOX"}
        url = f"/messaging/conversations"
        if createdBedore:
            url = url + "?createdBefore=" + str(createdBedore)
        res = self._fetch(url, params=params)
        return res.json()

linkedin = Linkedin('email', 'password')
conversations = linkedin.get_conversations()
        while len(conversations['elements']) > 0:
            if len(conversations['elements']) < 20:
                break
            else:
                conversations = linkedin.get_conversations(conversations['elements'][19]['events'][0]['createdAt'])

**Comment by AchatY** [comment]
Hello,
Here's how I managed to do it and it works very well

def get_conversations(self, createdBedore=None):
    """
    Return list of conversations the user is in.
    """
    params = {"keyVersion": "LEGACY_INBOX"}
    url = f"/messaging/conversations"
    if createdBedore:
        url = url + "?createdBefore=" + str(createdBedore)
    res = self._fetch(url, params=params)
    return res.json()

def main():
    linkedin = Linkedin('email', 'password')
    conversations = linkedin.get_conversations()
    while len(conversations['elements']) > 0:
        if len(conversations['elements']) < 20:
            break
    else:
        conversations = linkedin.get_conversations(conversations['elements'][19]['events'][0]['createdAt'])

**Comment by AchatY** [comment]
Hello,
Here's how I managed to do it and it works very well

    def main():
        linkedin = Linkedin('email', 'password')
        conversations = linkedin.get_conversations()
        while len(conversations['elements']) > 0:
            if len(conversations['elements']) < 20:
                break
        else:
            conversations = linkedin.get_conversations(conversations['elements'][19]['events'][0]['createdAt'])

    def get_conversations(self, createdBedore=None):
        """
        Return list of conversations the user is in.
        """
        params = {"keyVersion": "LEGACY_INBOX"}
        url = f"/messaging/conversations"
        if createdBedore:
            url = url + "?createdBefore=" + str(createdBedore)
        res = self._fetch(url, params=params)
        return res.json()

**Comment by YuriyRomanyshynUA** [comment]
Hi)

I would like to share what I have found:

url - www.linkedin.com/voyager/api/messaging/conversations?keyVersion=LEGACY_INBOX&q=participants&recipients=List(linkedin-member-urn)

method: GET
required headers:
csrf-token: token
x-restli-protocol-version: "2.0.0"

This link will return all conversations with given contact.
I consider this method to load conversations as more appropriate
because you do not need to process all user messaging history to load conversations

Simple implementation on JS to try in browser:

```javascript
async function conversations(csrfToken, contactUrn) {
    let url = 
        "https://www.linkedin.com/voyager/api/" +
	"messaging/conversations?" +
	"keyVersion=LEGACY_INBOX&"+
	"q=participants&" +
	"recipients=List(" + contactUrn + ")";

    let headers = {
	"csrf-token": csrfToken,
	"x-restli-protocol-version": "2.0.0"
    };

    let opt = {
	credentials: "include",
	headers: headers,
	method: "GET",
	mode: "cors"
    };

    let res = await fetch(url, opt);

    if(res.ok)
	return await res.json();
    else
	throw ("[Linkedin.api][conversations] Response failed!");
};
```

**Comment by Tabish-Invo** [comment]
Dose anyone find solution for this?

**Comment by kenuxi** [comment]
@Tabish-Invo what's the problem with the solution above?

**Comment by manuelrech** [comment]
if you copy and paste that it does not work, there is a very simple indentation error that once fixed for me worked on the `main()` function. The `else` statement should refer to the `if` therefore it has to be indented inside the `while` loop
