### ISSUE TITLE
API stopped connecting - LinkedinSessionExpired

### ISSUE THREAD

**Issue by fbuenohernandez** [tomquirk/linkedin-api#461]
```
from linkedin_api import Linkedin

# Authenticate using any Linkedin user account credentials
api = Linkedin('me@hotmail.com', 'mypass')

# GET a profile
profile = api.get_profile('billy-g')

  File ~\AppData\Roaming\Python\Python312\site-packages\linkedin_api\linkedin.py:287 in __init__
    self.client.authenticate(username, password)

  File ~\AppData\Roaming\Python\Python312\site-packages\linkedin_api\client.py:96 in authenticate
    cookies = self._cookie_repository.get(username)

  File ~\AppData\Roaming\Python\Python312\site-packages\linkedin_api\cookie_repository.py:36 in get
    raise LinkedinSessionExpired

LinkedinSessionExpired
```

Is it just me?

**Comment by fbuenohernandez** [comment]
Now I get:


  File ~\AppData\Roaming\Python\Python312\site-packages\linkedin_api\client.py:165 in _do_authentication_request
    raise ChallengeException(data["login_result"])

ChallengeException: CHALLENGE

**Comment by miniquinox** [comment]
Same for me

**Comment by Christian-BH** [comment]
Same happened to me today. Not sure when I last had it working. But I have not made any code changes or updates to my installed packages.

**Comment by fbuenohernandez** [comment]
@miniquinox @Christian-BH 

The issue is one of the cookies is already expired when it's created:

linkedin_api/cookie_repository.py -

` @staticmethod
    def _is_token_still_valid(cookiejar: RequestsCookieJar):
        _now = time.time()
        for cookie in cookiejar:
            if cookie.name == "JSESSIONID" and cookie.value:
                print("Cookie ", tstamp(cookie.expires), "Current time ", tstamp(_now))
                if cookie.expires and cookie.expires > _now:
                    return True
                break
        return False`

**Cookie  _2024-11-11 14:01:12_ Current time  2024-12-20 13:39:39**

I can't dig deeper into now, but forcing a true seems to help:

` @staticmethod
    def _is_token_still_valid(cookiejar: RequestsCookieJar):
        return True
        _now = time.time()
        for cookie in cookiejar:
            if cookie.name == "JSESSIONID" and cookie.value:
                if cookie.expires and cookie.expires > _now:
                    return True
                break

        return False`

Regards.

@tomquirk, do your thing!

**Comment by fbuenohernandez** [comment]
Go on:

C:\Users\YouUser\.linkedin_api\cookies and delete the cookie.

Regards.
