### ISSUE TITLE
How to get a cookie？

### ISSUE THREAD

**Issue by bestRunner** [tomquirk/linkedin-api#49]
https://www.linkedin.com/uas/authenticate，Excuse me how to pass the post parameters, can you refer to the examples?

**Comment by tomquirk** [comment]
Hey @buhuaqi , I don't quite understand your question. Relevant code for authentiation is [here](https://github.com/tomquirk/linkedin-api/blob/master/linkedin_api/client.py#L92)

**Comment by buhuaqi** [comment]
Thank you very much！Regarding personal information, how is the interface request limit?
https://www.linkedin.com/voyager/api/identity/profiles/%s/profileView

**Comment by buhuaqi** [comment]
The ban on this interface is very high, and the concurrent request is one hundred users, more than one hundred users will return null

**Comment by buhuaqi** [comment]
@tomquirk

**Comment by tomquirk** [comment]
@buhuaqi I'm very sorry but I'm struggling to understand your question. Are you having a problem, or is there something you want clarified?
