### ISSUE TITLE
Search filters not working for search_people

### ISSUE THREAD

**Issue by dicktalens** [tomquirk/linkedin-api#51]
When running search_people, parameters don't seem to be working. Instead, I get the same list that's returned when you search for your first degree connections.

I verified that the parameters were correct by replicating the search in browser and looking at the parameters with the calls made.

**Comment by favcau** [comment]
I had the same problem when I installed the api with `pip install linkedin-api`.
To solve this I installed it with `pip install -e git+https://github.com/tomquirk/linkedin-api.git` (in another env).
Now it's working. I'm using the params _keywords, industries, regions_ (at least those filters works, didn't check the others)

**Comment by tomquirk** [comment]
I'm going to assume this one is fixed. Please reopen if you think otherwise @dicktalens 😄
