### ISSUE TITLE
Getting ChallengeException(data["login_result"]) when running through Azure Functions

### ISSUE THREAD

**Issue by prakulgupta** [tomquirk/linkedin-api#53]
Locally client.py works but while running the same code through Azure function it gives below error -
Result: Failure
Exception: ChallengeException: CHALLENGE
Stack:   File "/usr/local/lib/python3.6/site-packages/azure/functions_worker/dispatcher.py", line 300, in _handle__invocation_request
    self.__run_sync_func, invocation_id, fi.func, args)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/azure/functions_worker/dispatcher.py", line 389, in __run_sync_func
    return func(**params)
  File "/home/site/wwwroot/connections/__init__.py", line 11, in main
    return getConnections(req)
  File "/home/site/wwwroot/connections/__init__.py", line 16, in getConnections
    api = Linkedin(content['email'],content['password'])
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/linkedin_api/linkedin.py", line 37, in __init__
    self.client.authenticate(username, password)
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/linkedin_api/client.py", line 116, in authenticate
    raise ChallengeException(data["login_result"])

**Comment by tomquirk** [comment]
Probably because the IP addr. of the Azure func. is different from what Linkedin expects it to be (i.e. your normal IP addr.). Nothing we can do about this at this time besides manually passing the challenge in a browser.

Certainly something we should try to implement eventually :)

**Comment by everping** [comment]
@prakulgupta 
That happened because you never logged in with the given account in that server before. I have written a script to handle it. I think it's too late for your case, but hopefully, it can help others.

https://github.com/everping/Linkedin-Authentication-Challenge

**Comment by err0or404** [comment]
@everping not working

**Comment by kidikudazi** [comment]
@apurvpatel2121 Good day, I wanted to ask if you later got a solution to this?

**Comment by Suhani-shri** [comment]
Hello, 
2 days ago its works on EC2 server, but now again its give challenge exception.

**Comment by baoguoding** [comment]
> @prakulgupta That happened because you never logged in with the given account in that server before. I have written a script to handle it. I think it's too late for your case, but hopefully, it can help others.
> 
> https://github.com/everping/Linkedin-Authentication-Challenge

This is correct. you can put it in your project, then 1st run, key in the pin code, that is done. 

After this to run the existing logic.

程序需要执行一次challenge,所以你把这个代码文件搞下来，输入用户名和密码，跑一次。

然后继续执行之前的程序就可以了。那个pin只要执行一次，做个验证。

希望对大家有帮助。
