### ISSUE TITLE
Is there a limit for api.get_profile_connections?

### ISSUE THREAD

**Issue by yunpeng-zhang** [tomquirk/linkedin-api#56]
Thanks for the API and it is very helpful. 

It seems that there is 1000 rate limit for how many profile it can pull for Distance_1 and Distance_2. Is there a way to bypass this pull limit? Thanks in advance.

**Comment by tomquirk** [comment]
Guys, I could give you all advice on scraping, however I do have to remind you of the [Ts and Cs](https://github.com/tomquirk/linkedin-api#usage) - you shouldn't use this project to store any PII).

You'll have to get creative if you want to bypass a multimillion dollar companies rate-limiting 😂
