### ISSUE TITLE
Add support for sending message attachments/files

### ISSUE THREAD

**Issue by kingbar1990** [tomquirk/linkedin-api#58]
I need to send files via send_message method but i can't understand how to upload  files to the LinkedIn storage ? have any assumptions about this ?

**Comment by tomquirk** [comment]
Its certainly possible, just not implemented. For future reference, after having a quick look, look like its these events (in order):
1. 
```
https://www.linkedin.com/voyager/api/voyagerMediaUploadMetadata?action=upload

payload:

{"mediaUploadType":"MESSAGING_PHOTO_ATTACHMENT","fileSize":22827,"filename":"Filename.png"}
```

That returns you URLs and some ID's which you can then use in send message

2. Send message with attacthments (use the ID from above, and use the same endpoint as sending a regular message, but use an `attachments` key

**Comment by abinpaul1** [comment]
Tracking in #196
