### ISSUE TITLE
search_people does not work properly

### ISSUE THREAD

**Issue by amerkay** [tomquirk/linkedin-api#59]
I found the bug [referenced here](https://github.com/tomquirk/linkedin-api/pull/35#issuecomment-474126423).

Change [L82](https://github.com/tomquirk/linkedin-api/blob/252add3bda1a9ce1f50fcd5419aac05dbf81498c/linkedin_api/linkedin.py#L82), adding `safe="(),"` to exclude problematic characters:
```py
res = self._fetch(
    "/search/blended?{}".format(urlencode(default_params, safe="(),")),
    headers={"accept": "application/vnd.linkedin.normalized+json+2.1"},
)
```

Great work on this library! :)

**Comment by tomquirk** [comment]
awesome, thanks for finding this @amerkay ! Happy to accept a PR for it if you like

**Comment by amerkay** [comment]
> awesome, thanks for finding this @amerkay ! Happy to accept a PR for it if you like

Done!
