### ISSUE TITLE
Can't get connections beyond 1000

### ISSUE THREAD

**Issue by xyshell** [tomquirk/linkedin-api#61]
I have a linkedin account which has 3000 first connections but get_profile_connections(urn_id=...) only gives me 1000 records? Can I get all the 3000 records?

**Comment by tomquirk** [comment]
Yea looks like we'll have to determine if we can page through profile connections. I'll slap the bug label on it 👍

**Comment by xyshell** [comment]
Cool，when do you expect to fix this?

**Comment by xyshell** [comment]
> Yea looks like we'll have to determine if we can page through profile connections. I'll slap the bug label on it 👍

**Comment by xyshell** [comment]
Cool, when do you expect to fix this?

**Comment by tomquirk** [comment]
I'd say within a month (assuming that it's actually possible) 👍

**Comment by MichaelAGunn** [comment]
I get an empty list from this method. Not sure what to do.

**Comment by tomquirk** [comment]
@akshayin I'm currently not working towards this, but happy to provide guidance for anyone willing.

**Comment by tomquirk** [comment]
This issue isn't solvable as far as I can tell. The API only returns the first 1000 results from any collection-based endpoint (connections, search, etc.)
