### ISSUE TITLE
Issue in reading/saving cookies - Ubuntu 14

### ISSUE THREAD

**Issue by Ulixestoitaca** [tomquirk/linkedin-api#62]
Hello,

there is an issue about saving/reading cookies in Ubuntu 14: cookies are not being saved totally and this causes a 401 error when API are used.

In windows it works fine but in Ubuntu I think pickle load/save has some char or encoding difference.

**Comment by marcelogrsp** [comment]
Hi @Ulixestoitaca might you provide your code here please? How are you getting cookies and using them?
