### ISSUE TITLE
Get engagers (likers/commenters) of a post

### ISSUE THREAD

**Issue by arthunterme** [tomquirk/linkedin-api#65]
I've been going through the code, and I don't think so, but just in case.

The idea would be to have two functions, one function to extract the shares of a particular user: https://www.linkedin.com/in/tom-quirk/detail/recent-activity/shares/

And output the LinkedIn share posts: https://www.linkedin.com/posts/tom-quirk_how-we-used-ai-to-translate-sign-language-activity-6449782512817446912-9X3U/ 

And another function that allows extracting the likers of the shares and outputs the id of the likers

Could this be the endpoint of the likers?

`https://www.linkedin.com/voyager/api/feed/reactions?count=10&q=reactionType&start=10&threadUrn=urn%3Ali%3Aactivity%3A6590338540985470976`

**Comment by arthunterme** [comment]
I got the likers: 

`    def get_likers(self, thread_id=None):
        
        res = self._fetch(f"/feed/reactions?count=10&q=reactionType&start=10&threadUrn={thread_id}")

        return res.json() `

The problem is that LinkedIn load only ten results at once, so I have failed to achieve a way to get all the likers.

**Comment by adnaanbheda** [comment]
You have count=10 as the query

**Comment by tomquirk** [comment]
We have function `get_post_reactions` now 

https://linkedin-api.readthedocs.io/en/latest/api.html#linkedin_api.Linkedin.get_post_reactions

Closing!
