### ISSUE TITLE
Linkedin function not working

### ISSUE THREAD

**Issue by marc233** [tomquirk/linkedin-api#70]
Hi tomquirk,

Thank you for your great package!
However, as a newbie, I met several problems since the install step. 

- It seems `-e` should be removed from the Installation step. 

- And after I load the package, I can't even use the first step by Linkedin function. For example, this is not working `api = Linkedin('reedhoffman@linkedin.com', 'iheartmicrosoft')`. And the error is `'CookieRepository' object has no attribute 'logger'`. 

I would be appreciated if you could tell me how to solve this problem. And my system is `Windows 10 pro`, `Python 3.7.3` with `Anaconda`.
Thanks for your reply!

Sheng

**Comment by tomquirk** [comment]
Apologies for that @marc233. I actually took the time to fix this properly 😅 Let me know how you go

**Comment by marc233** [comment]
> Apologies for that @marc233. I actually took the time to fix this properly 😅 Let me know how you go

Thanks a lot @tomquirk ! It works now! 
But I still some questions about the `public_id` and `URN_id`. For example, where can I get them, and is it possible to get other people's profile even if they are not my connections (for research)? It would be very nice if you could offer me some suggestions about how to get it.

**Comment by tomquirk** [comment]
so public_id is the id in the url. 

e.g. `www.linkedin.com/li/tom-quirk`, the public id is `tom-quirk`

If you get that profile using `linkedin.get_profile("tom-quirk")`, that's where you can get the URN id. They're 2 ID's that relate to the same entity, but you'll need to use one or the other depending on the circumstance :)

**Comment by marc233** [comment]
Hi Tom,

Thanks for your clear explanation!

I've tried the `public_id`, which really works well. 

However, for the `URN id`, the `linkedin.get_profile('public_id')` just return a JSON-like output. And there are so many URNs. Should I find it manually (like using `regex`) or there are some other methods? I've tried to put the JSON-like output into `get_profile_connections()` directly, which returns an error `KeyError: 'data'`. 

And here is the screenshot for your convenience.

![image](https://user-images.githubusercontent.com/38072719/66529081-03d68b80-ead0-11e9-81b6-46f260c63045.png)
![image](https://user-images.githubusercontent.com/38072719/66528900-7b57eb00-eacf-11e9-918c-f8a38a2752d7.png)
![image](https://user-images.githubusercontent.com/38072719/66528909-8579e980-eacf-11e9-93ad-fcc476e928a2.png)

Best regards,
Sheng

**Comment by tomquirk** [comment]
Hey Sheng, so `get_profile_connections` takes the `urn_id`. In your case, you can do something like
```python
profile = api.get_profile('public-profile-id')
connections = api.get_profile_connections(profile["profile_id")
```

Apologies for the lack of clarity around this in the docs - I'll make an issue to make it more obvious! Just know for now that URN ID's are usually those long uuid-like strings as opposed to the simple `tom-quirk`

**Comment by marc233** [comment]
Hi Tom, 

Thank you so much! I'll try it later.

Best regards,
Sheng

**Comment by foreandr** [comment]
this still does not work for me by the way

`connections = api.get_profile_connections(profile["profile_id"])` fails

as well as

```
        profile_id = profile["profile_id"]
        profile_urn_id = profile["profile_urn"]
        member_urn_id = profile["member_urn"]
```
