### ISSUE TITLE
Improve docs on difference between public and urn id's 

### ISSUE THREAD

**Issue by tomquirk** [tomquirk/linkedin-api#73]
#70 exposed an unclear-ness about what is a "public id" and what is a "urn id". We need to improve this in docs and in code

**Comment by MichaelAGunn** [comment]
Yes, I don't know how to derive the urn of an entity. I can't use methods that require the urn as an argument if I can't derive the urn.

**Comment by tomquirk** [comment]
@MichaelAGunn new docs, check them out! https://linkedin-api.readthedocs.io/en/latest/key_concepts.html#urn-id-vs-public-id
