### ISSUE TITLE
Exception in get company method

### ISSUE THREAD

**Issue by bevenky** [tomquirk/linkedin-api#75]
File "test.py", line 7, in <module>
    company = api.get_company('microsoft.com')
  File "/Users/linkedinapi_env/lib/pythonX.X/site-packages/linkedin_api/linkedin.py", line 481, in get_company
    self.logger.info("request failed: {}".format(data["message"]))
KeyError: 'message'

**Comment by naiktanmai** [comment]
+1 same issue here. Searching for fiverr.

**Comment by crouinicrouina** [comment]
Similar issue here : 

```
[...]
"linkedin.py", line 102, in search
    for i in range(len(data["data"]["elements"])):
KeyError: 'data'
```

**Comment by jeremy1392** [comment]
+1 bug...

**Comment by jeremy1392** [comment]
Error happens because you need to transform companyName value with blank which could be "Bla Bla" into "Bla-Bla"
You can fixe it by doing:

get_company(companyName.replace(" ", "-"))

**Comment by tomquirk** [comment]
Gotta pass in the company's "public id". You can get it from the URL when viewing the company

<img width="481" alt="Screenshot 2024-09-02 at 8 47 11 PM" src="https://github.com/user-attachments/assets/d8a44579-9731-4656-b836-64f288a7c855">
