### ISSUE TITLE
How to get the details of my connections

### ISSUE THREAD

**Issue by tbhaxor** [tomquirk/linkedin-api#77]
Hey there

I want to obtain the data of my connections like

- when they connected (1 days ago, etc)
- company
- occupation
- location

**Comment by tomquirk** [comment]
Company, occupation and location are possible. When they connected, I don't think that's possible.

The [`get_profile`](https://github.com/tomquirk/linkedin-api/blob/master/DOCS.md#get_profile) endpoint should get you most of the way
