### ISSUE TITLE
Add support for creating a new conversation

### ISSUE THREAD

**Issue by cyb3rsalih** [tomquirk/linkedin-api#85]
I can't send param's to this function. I notice that you put a comment line that

```
# passing 'params' doesn't work properly, think it's to do with List(). 
# Might be a bug in 'requests' ? 
``` 
Is there any quick fix for this? 
I really need this.

**Comment by cyb3rsalih** [comment]
After some test, I realize that, I can send message to anyone over api, only if I had a conversation before. Did you also figure out?
I open a for loop and traverse over my connections. Got this result for conversation. The successful tabs are the connections that I chat before. 
LOG
```
ACoAABN_***************uC5QHh9JPYatbQA Error
ACoAAAfI_***************GvrPiCWkBfgd_dUKs Error
ACoAAAL***************NWvu2ZoxQUqMLpCWmKA Success
ACoAACSO***************DTN_GDS80eebns4Goe3U Error
ACoAAC-iK***************wrlRDpgkCcgNejg Error
ACoAACB***************cctsdha8FoBMMtLewTh8 Error
ACoAACl9Ku***************AKhObTVMBJ9-Qdzr7PE Error
ACoAAA8Ho***************AXYpc9t09axoaIRfD8o Success
ACoAABzO***************eNUlw_nMGQ0TVTRo2I Error
ACoAAB_OH***************Aithdad2Qa_lySXSE8Ol4 Error
```

**Comment by jckw** [comment]
Did you figure out a work around @cyb3rsalih ?

**Comment by cyb3rsalih** [comment]
nope :(

**Comment by abinpaul1** [comment]
I think this is the endpoint for creating new conversations. After playing around a bit, I believe this endpoint returns the conversataion id if it already exists or creates one and returns it.
I am not sure what the `originToken` is though
```javascript
POST /voyager/api/messaging/conversations?action=create HTTP/1.1

{
  "keyVersion": "LEGACY_INBOX",
  "conversationCreate": {
    "eventCreate": {
      "originToken": "3876a9bc-812d-4c57-a9c4-ca29a8fbd81e",
      "value": {
        "com.linkedin.voyager.messaging.create.MessageCreate": {
          "attributedBody": {
            "text": "Hi",
            "attributes": []
          },
          "attachments": []
        }
      },
      "trackingId": "ØèÀÚÜós?Q}% µ¦Æ©"
    },
    "recipients": [
      "ACoAAC6tgzQBwZ78dWtE9WAYfWxjYWm9x8lYtJ0"
    ],
    "subtype": "MEMBER_TO_MEMBER"
  }
}
```

**Comment by kdhim** [comment]
@abinpaul1 @cyb3rsalih any luck on figuring out **originToken** and **trackingId**?

**Comment by abinpaul1** [comment]
> @abinpaul1 @cyb3rsalih any luck on figuring out **originToken** and **trackingId**?

`trackingId` is randomly generated. I have opened a pull request with a function to do the same in #136 .
I am not sure what the `originToken` is though. Hardcoding it and sending it might work.

**Comment by adeveloperhere** [comment]
> 
> 
> > @abinpaul1 @cyb3rsalih any luck on figuring out **originToken** and **trackingId**?
> 
> `trackingId` is randomly generated. I have opened a pull request with a function to do the same in #136 .
> I am not sure what the `originToken` is though. Hardcoding it and sending it might work.

originToken looks like GUID 
trackingId from source it says UInt8Array to base64 value but it does not work. 

Someone should look into this matter

**Comment by abinpaul1** [comment]
@cyb3rsalih @kdhim 
I have tried a fix for this in the linked pull request. Please do check and let me know if it works for you as well.

**Comment by abinpaul1** [comment]
Done in #171
