### ISSUE TITLE
Support ability to send Linkedin messages

### ISSUE THREAD

**Issue by tomquirk** [tomquirk/linkedin-api#9]
1. GET the conversation first to get the `conversationId`
  ```
  voyager/api/messaging/conversations? 
  keyVersion=LEGACY_INBOX&q=participants&recipients=List(<urn_id>)
  ```

2. POST to prove I'm typing
  ```
  voyager/api/messaging/conversations?action=typing
  data = {
    "conversationId":"1234506060"
  }
  ```

3. POST to send the message
url:
```
/voyager/api/messaging/conversations/<conversationId>/events?action=create
```

```json
{"eventCreate":{"value":{"com.linkedin.voyager.messaging.create.MessageCreate":{"body":"test","attachments":[],"attributedBody":{"text":"test","attributes":[]},"mediaAttachments":[]}}}}
```

**Comment by tomquirk** [comment]
Done

**Comment by adeveloperhere** [comment]
The conversations endpoint is no longer OK. Now it requires new tracking ID and originToken, can you please fix it?

**Comment by tomquirk** [comment]
Please open a new issue if there is a new bug, and please consider submitting a fix! 🙏

**Comment by adeveloperhere** [comment]
> 
> 
> Please open a new issue if there is a new bug, and please consider submitting a fix! 🙏

I have posted investigation data and someone knows JS well can fix it.
Issue link here https://github.com/tomquirk/linkedin-api/issues/168

**Comment by DeanVanGreunen** [comment]
Hi, so lets say I have this user id **M2I1ZDVmYzctNWM3Yi00MmYwLWEyYmMtNTFjY2NiOTFiMjIwXzAxMA** and i have the **li_at** and the **jsessionid** (csrf-token)

and I want to send a message such as "Hi" what apis do I call?
