### ISSUE TITLE
Missing experiences 

### ISSUE THREAD

**Issue by sorasful** [tomquirk/linkedin-api#90]
Hello guys ! 

I was using the `get_profile` method to fetch information like experiences or education. But it seems that when people have a lot of experiences, on the website there's a button "Show more", these information are not in the JSON response.  

So I dug into it, and it seems there is another URL we can use there which contains everything (I think).

It's `/voyager/api/identity/dash/profiles?q=memberIdentity&memberIdentity=NAME&decorationId=com.linkedin.voyager.dash.deco.identity.profile.FullProfileWithEntities-47` 

Apparently, the number goes from 1 to 47 and it gives different information. I should dig more to understand the differences.   

Are you aware of this behavior ? Did you know about this URL ? If we find it relevant, I can make a PR.

Cheers  !

**Comment by tomquirk** [comment]
@sorasful thanks for investigating this, I was not aware of this URL. Please feel free to submit a PR, I would happily review it! 😁

**Comment by bilaladak** [comment]
Did you have chance to check this bug ?

**Comment by sorasful** [comment]
@bilaladak It's been a while, as far as I remember I did not investigate more than what I wrote on this issue.

**Comment by ruffinellimarco** [comment]
@sorasful @bilaladak I wanted to check in on this as I'm going to start investigating this myself, but did you guys end up finding anything first?

**Comment by Prii-y** [comment]
Was anyone able to solve this ?

**Comment by Prii-y** [comment]
@sorasful  were u able to find another alternative for it outside the API would love any advice on how  I can proceed coz I need all the experiences for my research.
