### ISSUE TITLE
How to i fix `ChallengeException`

### ISSUE THREAD

**Issue by pidugusundeep** [tomquirk/linkedin-api#96]
I constantly get this exception while authenticating my account. How do I fix this?
```
  File "/workspace/linkedin-api/linkedin_api/client.py", line 122, in _do_authentication_request
    raise ChallengeException(data["login_result"])
linkedin_api.client.ChallengeException: CHALLENGE
```

**Comment by err0or404** [comment]
yes same error

**Comment by tomquirk** [comment]
See README: https://github.com/tomquirk/linkedin-api#i-keep-getting-a-challenge

**Comment by Nasim004** [comment]
I am not getting any CHALLENGE in my local but when I run in other system I am getting the CHALLENGE error.

Is anyone got the solution ???
